// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: service/database_registry/protos/database_registry.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDatabaseRequest) Reset() {
	*x = EnsureDatabaseRequest{}
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDatabaseRequest) ProtoMessage() {}

func (x *EnsureDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDatabaseRequest.ProtoReflect.Descriptor instead.
func (*EnsureDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_service_database_registry_protos_database_registry_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

type EnsureDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDatabaseResponse) Reset() {
	*x = EnsureDatabaseResponse{}
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDatabaseResponse) ProtoMessage() {}

func (x *EnsureDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDatabaseResponse.ProtoReflect.Descriptor instead.
func (*EnsureDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_service_database_registry_protos_database_registry_proto_rawDescGZIP(), []int{1}
}

type EnsureTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	TableId       string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	TableType     string                 `protobuf:"bytes,3,opt,name=table_type,json=tableType,proto3" json:"table_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureTableRequest) Reset() {
	*x = EnsureTableRequest{}
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTableRequest) ProtoMessage() {}

func (x *EnsureTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTableRequest.ProtoReflect.Descriptor instead.
func (*EnsureTableRequest) Descriptor() ([]byte, []int) {
	return file_service_database_registry_protos_database_registry_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureTableRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *EnsureTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *EnsureTableRequest) GetTableType() string {
	if x != nil {
		return x.TableType
	}
	return ""
}

type EnsureTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureTableResponse) Reset() {
	*x = EnsureTableResponse{}
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTableResponse) ProtoMessage() {}

func (x *EnsureTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTableResponse.ProtoReflect.Descriptor instead.
func (*EnsureTableResponse) Descriptor() ([]byte, []int) {
	return file_service_database_registry_protos_database_registry_proto_rawDescGZIP(), []int{3}
}

var File_service_database_registry_protos_database_registry_proto protoreflect.FileDescriptor

const file_service_database_registry_protos_database_registry_proto_rawDesc = "" +
	"\n" +
	"8service/database_registry/protos/database_registry.proto\x12\x19database_registry_service\"8\n" +
	"\x15EnsureDatabaseRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\"\x18\n" +
	"\x16EnsureDatabaseResponse\"o\n" +
	"\x12EnsureTableRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"table_type\x18\x03 \x01(\tR\ttableType\"\x15\n" +
	"\x13EnsureTableResponse2\xfe\x01\n" +
	"\x17DatabaseRegistryService\x12u\n" +
	"\x0eEnsureDatabase\x120.database_registry_service.EnsureDatabaseRequest\x1a1.database_registry_service.EnsureDatabaseResponse\x12l\n" +
	"\vEnsureTable\x12-.database_registry_service.EnsureTableRequest\x1a..database_registry_service.EnsureTableResponseB8Z6sentioxyz/sentio-core/service/database_registry/protosb\x06proto3"

var (
	file_service_database_registry_protos_database_registry_proto_rawDescOnce sync.Once
	file_service_database_registry_protos_database_registry_proto_rawDescData []byte
)

func file_service_database_registry_protos_database_registry_proto_rawDescGZIP() []byte {
	file_service_database_registry_protos_database_registry_proto_rawDescOnce.Do(func() {
		file_service_database_registry_protos_database_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_database_registry_protos_database_registry_proto_rawDesc), len(file_service_database_registry_protos_database_registry_proto_rawDesc)))
	})
	return file_service_database_registry_protos_database_registry_proto_rawDescData
}

var file_service_database_registry_protos_database_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_database_registry_protos_database_registry_proto_goTypes = []any{
	(*EnsureDatabaseRequest)(nil),  // 0: database_registry_service.EnsureDatabaseRequest
	(*EnsureDatabaseResponse)(nil), // 1: database_registry_service.EnsureDatabaseResponse
	(*EnsureTableRequest)(nil),     // 2: database_registry_service.EnsureTableRequest
	(*EnsureTableResponse)(nil),    // 3: database_registry_service.EnsureTableResponse
}
var file_service_database_registry_protos_database_registry_proto_depIdxs = []int32{
	0, // 0: database_registry_service.DatabaseRegistryService.EnsureDatabase:input_type -> database_registry_service.EnsureDatabaseRequest
	2, // 1: database_registry_service.DatabaseRegistryService.EnsureTable:input_type -> database_registry_service.EnsureTableRequest
	1, // 2: database_registry_service.DatabaseRegistryService.EnsureDatabase:output_type -> database_registry_service.EnsureDatabaseResponse
	3, // 3: database_registry_service.DatabaseRegistryService.EnsureTable:output_type -> database_registry_service.EnsureTableResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_database_registry_protos_database_registry_proto_init() }
func file_service_database_registry_protos_database_registry_proto_init() {
	if File_service_database_registry_protos_database_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_database_registry_protos_database_registry_proto_rawDesc), len(file_service_database_registry_protos_database_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_database_registry_protos_database_registry_proto_goTypes,
		DependencyIndexes: file_service_database_registry_protos_database_registry_proto_depIdxs,
		MessageInfos:      file_service_database_registry_protos_database_registry_proto_msgTypes,
	}.Build()
	File_service_database_registry_protos_database_registry_proto = out.File
	file_service_database_registry_protos_database_registry_proto_goTypes = nil
	file_service_database_registry_protos_database_registry_proto_depIdxs = nil
}
