// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: service/database_registry/protos/database_registry.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseRegistryService_EnsureDatabase_FullMethodName     = "/database_registry_service.DatabaseRegistryService/EnsureDatabase"
	DatabaseRegistryService_EnsureTable_FullMethodName        = "/database_registry_service.DatabaseRegistryService/EnsureTable"
	DatabaseRegistryService_CreateUserDatabase_FullMethodName = "/database_registry_service.DatabaseRegistryService/CreateUserDatabase"
)

// DatabaseRegistryServiceClient is the client API for DatabaseRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabaseRegistryServiceClient interface {
	EnsureDatabase(ctx context.Context, in *EnsureDatabaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EnsureTable(ctx context.Context, in *EnsureTableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateUserDatabase(ctx context.Context, in *CreateUserDatabaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type databaseRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseRegistryServiceClient(cc grpc.ClientConnInterface) DatabaseRegistryServiceClient {
	return &databaseRegistryServiceClient{cc}
}

func (c *databaseRegistryServiceClient) EnsureDatabase(ctx context.Context, in *EnsureDatabaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DatabaseRegistryService_EnsureDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRegistryServiceClient) EnsureTable(ctx context.Context, in *EnsureTableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DatabaseRegistryService_EnsureTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseRegistryServiceClient) CreateUserDatabase(ctx context.Context, in *CreateUserDatabaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DatabaseRegistryService_CreateUserDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseRegistryServiceServer is the server API for DatabaseRegistryService service.
// All implementations must embed UnimplementedDatabaseRegistryServiceServer
// for forward compatibility.
type DatabaseRegistryServiceServer interface {
	EnsureDatabase(context.Context, *EnsureDatabaseRequest) (*emptypb.Empty, error)
	EnsureTable(context.Context, *EnsureTableRequest) (*emptypb.Empty, error)
	CreateUserDatabase(context.Context, *CreateUserDatabaseRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDatabaseRegistryServiceServer()
}

// UnimplementedDatabaseRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseRegistryServiceServer struct{}

func (UnimplementedDatabaseRegistryServiceServer) EnsureDatabase(context.Context, *EnsureDatabaseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureDatabase not implemented")
}
func (UnimplementedDatabaseRegistryServiceServer) EnsureTable(context.Context, *EnsureTableRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureTable not implemented")
}
func (UnimplementedDatabaseRegistryServiceServer) CreateUserDatabase(context.Context, *CreateUserDatabaseRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserDatabase not implemented")
}
func (UnimplementedDatabaseRegistryServiceServer) mustEmbedUnimplementedDatabaseRegistryServiceServer() {
}
func (UnimplementedDatabaseRegistryServiceServer) testEmbeddedByValue() {}

// UnsafeDatabaseRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseRegistryServiceServer will
// result in compilation errors.
type UnsafeDatabaseRegistryServiceServer interface {
	mustEmbedUnimplementedDatabaseRegistryServiceServer()
}

func RegisterDatabaseRegistryServiceServer(s grpc.ServiceRegistrar, srv DatabaseRegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDatabaseRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseRegistryService_ServiceDesc, srv)
}

func _DatabaseRegistryService_EnsureDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRegistryServiceServer).EnsureDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseRegistryService_EnsureDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRegistryServiceServer).EnsureDatabase(ctx, req.(*EnsureDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRegistryService_EnsureTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRegistryServiceServer).EnsureTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseRegistryService_EnsureTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRegistryServiceServer).EnsureTable(ctx, req.(*EnsureTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseRegistryService_CreateUserDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseRegistryServiceServer).CreateUserDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseRegistryService_CreateUserDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseRegistryServiceServer).CreateUserDatabase(ctx, req.(*CreateUserDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseRegistryService_ServiceDesc is the grpc.ServiceDesc for DatabaseRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "database_registry_service.DatabaseRegistryService",
	HandlerType: (*DatabaseRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureDatabase",
			Handler:    _DatabaseRegistryService_EnsureDatabase_Handler,
		},
		{
			MethodName: "EnsureTable",
			Handler:    _DatabaseRegistryService_EnsureTable_Handler,
		},
		{
			MethodName: "CreateUserDatabase",
			Handler:    _DatabaseRegistryService_CreateUserDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/database_registry/protos/database_registry.proto",
}
