// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: service/database_registry/protos/database_registry.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorId   string                 `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	ReplicaIndex  uint32                 `protobuf:"varint,2,opt,name=replica_index,json=replicaIndex,proto3" json:"replica_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDatabaseRequest) Reset() {
	*x = EnsureDatabaseRequest{}
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDatabaseRequest) ProtoMessage() {}

func (x *EnsureDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDatabaseRequest.ProtoReflect.Descriptor instead.
func (*EnsureDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_service_database_registry_protos_database_registry_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureDatabaseRequest) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *EnsureDatabaseRequest) GetReplicaIndex() uint32 {
	if x != nil {
		return x.ReplicaIndex
	}
	return 0
}

type EnsureTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorId   string                 `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	ReplicaIndex  uint32                 `protobuf:"varint,2,opt,name=replica_index,json=replicaIndex,proto3" json:"replica_index,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	TableType     string                 `protobuf:"bytes,4,opt,name=table_type,json=tableType,proto3" json:"table_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureTableRequest) Reset() {
	*x = EnsureTableRequest{}
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTableRequest) ProtoMessage() {}

func (x *EnsureTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_database_registry_protos_database_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTableRequest.ProtoReflect.Descriptor instead.
func (*EnsureTableRequest) Descriptor() ([]byte, []int) {
	return file_service_database_registry_protos_database_registry_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureTableRequest) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *EnsureTableRequest) GetReplicaIndex() uint32 {
	if x != nil {
		return x.ReplicaIndex
	}
	return 0
}

func (x *EnsureTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *EnsureTableRequest) GetTableType() string {
	if x != nil {
		return x.TableType
	}
	return ""
}

var File_service_database_registry_protos_database_registry_proto protoreflect.FileDescriptor

const file_service_database_registry_protos_database_registry_proto_rawDesc = "" +
	"\n" +
	"8service/database_registry/protos/database_registry.proto\x12\x19database_registry_service\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x15EnsureDatabaseRequest\x12!\n" +
	"\fprocessor_id\x18\x01 \x01(\tR\vprocessorId\x12#\n" +
	"\rreplica_index\x18\x02 \x01(\rR\freplicaIndex\"\x96\x01\n" +
	"\x12EnsureTableRequest\x12!\n" +
	"\fprocessor_id\x18\x01 \x01(\tR\vprocessorId\x12#\n" +
	"\rreplica_index\x18\x02 \x01(\rR\freplicaIndex\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"table_type\x18\x04 \x01(\tR\ttableType2\xcb\x01\n" +
	"\x17DatabaseRegistryService\x12Z\n" +
	"\x0eEnsureDatabase\x120.database_registry_service.EnsureDatabaseRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\vEnsureTable\x12-.database_registry_service.EnsureTableRequest\x1a\x16.google.protobuf.EmptyB8Z6sentioxyz/sentio-core/service/database_registry/protosb\x06proto3"

var (
	file_service_database_registry_protos_database_registry_proto_rawDescOnce sync.Once
	file_service_database_registry_protos_database_registry_proto_rawDescData []byte
)

func file_service_database_registry_protos_database_registry_proto_rawDescGZIP() []byte {
	file_service_database_registry_protos_database_registry_proto_rawDescOnce.Do(func() {
		file_service_database_registry_protos_database_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_database_registry_protos_database_registry_proto_rawDesc), len(file_service_database_registry_protos_database_registry_proto_rawDesc)))
	})
	return file_service_database_registry_protos_database_registry_proto_rawDescData
}

var file_service_database_registry_protos_database_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_database_registry_protos_database_registry_proto_goTypes = []any{
	(*EnsureDatabaseRequest)(nil), // 0: database_registry_service.EnsureDatabaseRequest
	(*EnsureTableRequest)(nil),    // 1: database_registry_service.EnsureTableRequest
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_service_database_registry_protos_database_registry_proto_depIdxs = []int32{
	0, // 0: database_registry_service.DatabaseRegistryService.EnsureDatabase:input_type -> database_registry_service.EnsureDatabaseRequest
	1, // 1: database_registry_service.DatabaseRegistryService.EnsureTable:input_type -> database_registry_service.EnsureTableRequest
	2, // 2: database_registry_service.DatabaseRegistryService.EnsureDatabase:output_type -> google.protobuf.Empty
	2, // 3: database_registry_service.DatabaseRegistryService.EnsureTable:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_database_registry_protos_database_registry_proto_init() }
func file_service_database_registry_protos_database_registry_proto_init() {
	if File_service_database_registry_protos_database_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_database_registry_protos_database_registry_proto_rawDesc), len(file_service_database_registry_protos_database_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_database_registry_protos_database_registry_proto_goTypes,
		DependencyIndexes: file_service_database_registry_protos_database_registry_proto_depIdxs,
		MessageInfos:      file_service_database_registry_protos_database_registry_proto_msgTypes,
	}.Build()
	File_service_database_registry_protos_database_registry_proto = out.File
	file_service_database_registry_protos_database_registry_proto_goTypes = nil
	file_service_database_registry_protos_database_registry_proto_depIdxs = nil
}
