// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: service/webhook/protos/webhook_service.proto

package protos

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	protos "sentioxyz/sentio-core/service/common/protos"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorId   string                 `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessorId   string                 `protobuf:"bytes,1,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteSubscriptionRequest) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

type SaveChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveChannelRequest) Reset() {
	*x = SaveChannelRequest{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChannelRequest) ProtoMessage() {}

func (x *SaveChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChannelRequest.ProtoReflect.Descriptor instead.
func (*SaveChannelRequest) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveChannelRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SaveChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteChannelRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDeadletterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to GetProjectBy:
	//
	//	*GetDeadletterRequest_ProjectId
	//	*GetDeadletterRequest_OwnerAndSlug
	GetProjectBy  isGetDeadletterRequest_GetProjectBy `protobuf_oneof:"get_project_by"`
	Limit         int32                               `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeadletterRequest) Reset() {
	*x = GetDeadletterRequest{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeadletterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeadletterRequest) ProtoMessage() {}

func (x *GetDeadletterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeadletterRequest.ProtoReflect.Descriptor instead.
func (*GetDeadletterRequest) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeadletterRequest) GetGetProjectBy() isGetDeadletterRequest_GetProjectBy {
	if x != nil {
		return x.GetProjectBy
	}
	return nil
}

func (x *GetDeadletterRequest) GetProjectId() string {
	if x != nil {
		if x, ok := x.GetProjectBy.(*GetDeadletterRequest_ProjectId); ok {
			return x.ProjectId
		}
	}
	return ""
}

func (x *GetDeadletterRequest) GetOwnerAndSlug() *protos.ProjectOwnerAndSlug {
	if x != nil {
		if x, ok := x.GetProjectBy.(*GetDeadletterRequest_OwnerAndSlug); ok {
			return x.OwnerAndSlug
		}
	}
	return nil
}

func (x *GetDeadletterRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type isGetDeadletterRequest_GetProjectBy interface {
	isGetDeadletterRequest_GetProjectBy()
}

type GetDeadletterRequest_ProjectId struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3,oneof"`
}

type GetDeadletterRequest_OwnerAndSlug struct {
	OwnerAndSlug *protos.ProjectOwnerAndSlug `protobuf:"bytes,2,opt,name=owner_and_slug,json=ownerAndSlug,proto3,oneof"`
}

func (*GetDeadletterRequest_ProjectId) isGetDeadletterRequest_GetProjectBy() {}

func (*GetDeadletterRequest_OwnerAndSlug) isGetDeadletterRequest_GetProjectBy() {}

type GetDeadletterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeadletterResponse) Reset() {
	*x = GetDeadletterResponse{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeadletterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeadletterResponse) ProtoMessage() {}

func (x *GetDeadletterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeadletterResponse.ProtoReflect.Descriptor instead.
func (*GetDeadletterResponse) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeadletterResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_service_webhook_protos_webhook_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_service_webhook_protos_webhook_service_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Message) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_service_webhook_protos_webhook_service_proto protoreflect.FileDescriptor

const file_service_webhook_protos_webhook_service_proto_rawDesc = "" +
	"\n" +
	",service/webhook/protos/webhook_service.proto\x12\x0fwebhook_service\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\"service/common/protos/common.proto\">\n" +
	"\x19CreateSubscriptionRequest\x12!\n" +
	"\fprocessor_id\x18\x01 \x01(\tR\vprocessorId\">\n" +
	"\x19DeleteSubscriptionRequest\x12!\n" +
	"\fprocessor_id\x18\x01 \x01(\tR\vprocessorId\"G\n" +
	"\x12SaveChannelRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"I\n" +
	"\x14DeleteChannelRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa4\x01\n" +
	"\x14GetDeadletterRequest\x12\x1f\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tH\x00R\tprojectId\x12C\n" +
	"\x0eowner_and_slug\x18\x02 \x01(\v2\x1b.common.ProjectOwnerAndSlugH\x00R\fownerAndSlug\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\x10\n" +
	"\x0eget_project_by\"M\n" +
	"\x15GetDeadletterResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.webhook_service.MessageR\bmessages\"\xb6\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12H\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2(.webhook_service.Message.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc2\x04\n" +
	"\x0eWebhookService\x12X\n" +
	"\x12CreateSubscription\x12*.webhook_service.CreateSubscriptionRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x12DeleteSubscription\x12*.webhook_service.DeleteSubscriptionRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\vSaveChannel\x12#.webhook_service.SaveChannelRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rDeleteChannel\x12%.webhook_service.DeleteChannelRequest\x1a\x16.google.protobuf.Empty\x12\xdf\x01\n" +
	"\rGetDeadletter\x12%.webhook_service.GetDeadletterRequest\x1a&.webhook_service.GetDeadletterResponse\"\x7f\x82\xd3\xe4\x93\x02yZ)\x12'/api/v1/webhook/deadletter/{project_id}\x12L/api/v1/webhook/deadletter/{owner_and_slug.owner_name}/{owner_and_slug.slug}B.Z,sentioxyz/sentio-core/service/webhook/protosb\x06proto3"

var (
	file_service_webhook_protos_webhook_service_proto_rawDescOnce sync.Once
	file_service_webhook_protos_webhook_service_proto_rawDescData []byte
)

func file_service_webhook_protos_webhook_service_proto_rawDescGZIP() []byte {
	file_service_webhook_protos_webhook_service_proto_rawDescOnce.Do(func() {
		file_service_webhook_protos_webhook_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_webhook_protos_webhook_service_proto_rawDesc), len(file_service_webhook_protos_webhook_service_proto_rawDesc)))
	})
	return file_service_webhook_protos_webhook_service_proto_rawDescData
}

var file_service_webhook_protos_webhook_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_webhook_protos_webhook_service_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil),  // 0: webhook_service.CreateSubscriptionRequest
	(*DeleteSubscriptionRequest)(nil),  // 1: webhook_service.DeleteSubscriptionRequest
	(*SaveChannelRequest)(nil),         // 2: webhook_service.SaveChannelRequest
	(*DeleteChannelRequest)(nil),       // 3: webhook_service.DeleteChannelRequest
	(*GetDeadletterRequest)(nil),       // 4: webhook_service.GetDeadletterRequest
	(*GetDeadletterResponse)(nil),      // 5: webhook_service.GetDeadletterResponse
	(*Message)(nil),                    // 6: webhook_service.Message
	nil,                                // 7: webhook_service.Message.AttributesEntry
	(*protos.ProjectOwnerAndSlug)(nil), // 8: common.ProjectOwnerAndSlug
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_service_webhook_protos_webhook_service_proto_depIdxs = []int32{
	8, // 0: webhook_service.GetDeadletterRequest.owner_and_slug:type_name -> common.ProjectOwnerAndSlug
	6, // 1: webhook_service.GetDeadletterResponse.messages:type_name -> webhook_service.Message
	7, // 2: webhook_service.Message.attributes:type_name -> webhook_service.Message.AttributesEntry
	0, // 3: webhook_service.WebhookService.CreateSubscription:input_type -> webhook_service.CreateSubscriptionRequest
	1, // 4: webhook_service.WebhookService.DeleteSubscription:input_type -> webhook_service.DeleteSubscriptionRequest
	2, // 5: webhook_service.WebhookService.SaveChannel:input_type -> webhook_service.SaveChannelRequest
	3, // 6: webhook_service.WebhookService.DeleteChannel:input_type -> webhook_service.DeleteChannelRequest
	4, // 7: webhook_service.WebhookService.GetDeadletter:input_type -> webhook_service.GetDeadletterRequest
	9, // 8: webhook_service.WebhookService.CreateSubscription:output_type -> google.protobuf.Empty
	9, // 9: webhook_service.WebhookService.DeleteSubscription:output_type -> google.protobuf.Empty
	9, // 10: webhook_service.WebhookService.SaveChannel:output_type -> google.protobuf.Empty
	9, // 11: webhook_service.WebhookService.DeleteChannel:output_type -> google.protobuf.Empty
	5, // 12: webhook_service.WebhookService.GetDeadletter:output_type -> webhook_service.GetDeadletterResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_webhook_protos_webhook_service_proto_init() }
func file_service_webhook_protos_webhook_service_proto_init() {
	if File_service_webhook_protos_webhook_service_proto != nil {
		return
	}
	file_service_webhook_protos_webhook_service_proto_msgTypes[4].OneofWrappers = []any{
		(*GetDeadletterRequest_ProjectId)(nil),
		(*GetDeadletterRequest_OwnerAndSlug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_webhook_protos_webhook_service_proto_rawDesc), len(file_service_webhook_protos_webhook_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_webhook_protos_webhook_service_proto_goTypes,
		DependencyIndexes: file_service_webhook_protos_webhook_service_proto_depIdxs,
		MessageInfos:      file_service_webhook_protos_webhook_service_proto_msgTypes,
	}.Build()
	File_service_webhook_protos_webhook_service_proto = out.File
	file_service_webhook_protos_webhook_service_proto_goTypes = nil
	file_service_webhook_protos_webhook_service_proto_depIdxs = nil
}
