package ethereum

import (
	"fmt"
	"github.com/pkg/errors"
	"sentioxyz/sentio-core/common/utils"
	"sentioxyz/sentio-core/common/wasm"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
)

type EventParam struct {
	Name  *wasm.String
	Value *Value
}

func BuildEventParam(name string, value *Value) *EventParam {
	return &EventParam{
		Name:  wasm.BuildString(name),
		Value: value,
	}
}

func (ep *EventParam) String() string {
	if ep == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%s: %s", ep.Name.String(), ep.Value.String())
}

func (ep *EventParam) Dump(mm *wasm.MemoryManager) wasm.Pointer {
	return mm.DumpObject(ep)
}

func (ep *EventParam) Load(mm *wasm.MemoryManager, p wasm.Pointer) {
	mm.LoadObject(p, ep)
}

func MustConvertEventParam(value any, arg abi.Argument) *EventParam {
	param := &EventParam{Name: wasm.BuildString(arg.Name)}
	if arg.Indexed {
		// Refer to abi.ParseTopicsIntoMap
		switch arg.Type.T {
		case abi.TupleTy:
			panic(errors.Errorf("unreachable, " +
				"if arg is indexed and the type of it is tuple, abi.ParseTopicsIntoMap will return error"))
		case abi.StringTy, abi.BytesTy, abi.SliceTy, abi.ArrayTy:
			// Although it is very strange, the code generated by `graph codegen` uses the Bytes type,
			// and abi.ParseTopicsIntoMap convert the raw topics (type is common.Hash) as argument value
			hash := value.(common.Hash)
			param.Value = &Value{
				Kind:  ValueKindBytes,
				Value: &wasm.ByteArray{Data: hash[:]},
			}
			return param
		case abi.FunctionTy:
			// Similar to the case above
			fn := value.([24]byte)
			param.Value = &Value{
				Kind:  ValueKindBytes,
				Value: &wasm.ByteArray{Data: fn[:]},
			}
			return param
		}
	}
	param.Value = &Value{}
	param.Value.FromGoType(value, arg.Type)
	return param
}

type EventParams struct {
	wasm.ObjectArray[*EventParam]
}

func (eps *EventParams) Text(delimiter string) string {
	if eps == nil {
		return "<nil>"
	}
	return utils.ShowArray(eps.Data, delimiter)
}

func (eps *EventParams) String() string {
	return eps.Text(", ")
}

func BuildEventParams(params ...*EventParam) *EventParams {
	return &EventParams{ObjectArray: wasm.ObjectArray[*EventParam]{Data: params}}
}
