// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: service/project/protos/project_service.proto

package protos

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	protos "sentioxyz/sentio-core/service/common/protos"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProjectByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectByIdRequest) Reset() {
	*x = GetProjectByIdRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectByIdRequest) ProtoMessage() {}

func (x *GetProjectByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProjectByIdRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectByIdRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *protos.Project        `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Permissions   []protos.Permission    `protobuf:"varint,2,rep,packed,name=permissions,proto3,enum=common.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectResponse) GetProject() *protos.Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *GetProjectResponse) GetPermissions() []protos.Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ProjectOwnerAndSlug struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectOwnerAndSlug) Reset() {
	*x = ProjectOwnerAndSlug{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectOwnerAndSlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectOwnerAndSlug) ProtoMessage() {}

func (x *ProjectOwnerAndSlug) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectOwnerAndSlug.ProtoReflect.Descriptor instead.
func (*ProjectOwnerAndSlug) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectOwnerAndSlug) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *ProjectOwnerAndSlug) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CheckOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOwnerRequest) Reset() {
	*x = CheckOwnerRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOwnerRequest) ProtoMessage() {}

func (x *CheckOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOwnerRequest.ProtoReflect.Descriptor instead.
func (*CheckOwnerRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckOwnerRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsTaken       bool                   `protobuf:"varint,1,opt,name=is_taken,json=isTaken,proto3" json:"is_taken,omitempty"`
	IsValid       bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckResponse) GetIsTaken() bool {
	if x != nil {
		return x.IsTaken
	}
	return false
}

func (x *CheckResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type GetProjectListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProjectListRequest) Reset() {
	*x = GetProjectListRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectListRequest) ProtoMessage() {}

func (x *GetProjectListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectListRequest.ProtoReflect.Descriptor instead.
func (*GetProjectListRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetProjectListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProjectListRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetProjectListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Projects       []*protos.Project      `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	SharedProjects []*protos.Project      `protobuf:"bytes,2,rep,name=shared_projects,json=sharedProjects,proto3" json:"shared_projects,omitempty"`
	OrgProjects    []*protos.Project      `protobuf:"bytes,3,rep,name=org_projects,json=orgProjects,proto3" json:"org_projects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProjectListResponse) Reset() {
	*x = GetProjectListResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectListResponse) ProtoMessage() {}

func (x *GetProjectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectListResponse.ProtoReflect.Descriptor instead.
func (*GetProjectListResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetProjectListResponse) GetProjects() []*protos.Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *GetProjectListResponse) GetSharedProjects() []*protos.Project {
	if x != nil {
		return x.SharedProjects
	}
	return nil
}

func (x *GetProjectListResponse) GetOrgProjects() []*protos.Project {
	if x != nil {
		return x.OrgProjects
	}
	return nil
}

type ProjectMemberRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UsernameOrEmail string                 `protobuf:"bytes,2,opt,name=username_or_email,json=usernameOrEmail,proto3" json:"username_or_email,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectMemberRequest) Reset() {
	*x = ProjectMemberRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberRequest) ProtoMessage() {}

func (x *ProjectMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectMemberRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMemberRequest) GetUsernameOrEmail() string {
	if x != nil {
		return x.UsernameOrEmail
	}
	return ""
}

type ProjectMemberResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Members       []*protos.Project_ProjectMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberResponse) Reset() {
	*x = ProjectMemberResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberResponse) ProtoMessage() {}

func (x *ProjectMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectMemberResponse) GetMembers() []*protos.Project_ProjectMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ProjectViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Views         []*protos.ProjectView  `protobuf:"bytes,2,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectViewResponse) Reset() {
	*x = ProjectViewResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectViewResponse) ProtoMessage() {}

func (x *ProjectViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectViewResponse.ProtoReflect.Descriptor instead.
func (*ProjectViewResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectViewResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectViewResponse) GetViews() []*protos.ProjectView {
	if x != nil {
		return x.Views
	}
	return nil
}

type ImportProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerName      string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Slug           string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ImportProject  *ProjectOwnerAndSlug   `protobuf:"bytes,4,opt,name=import_project,json=importProject,proto3" json:"import_project,omitempty"`
	ImportProjects []*ProjectOwnerAndSlug `protobuf:"bytes,5,rep,name=import_projects,json=importProjects,proto3" json:"import_projects,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportProjectRequest) Reset() {
	*x = ImportProjectRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProjectRequest) ProtoMessage() {}

func (x *ImportProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProjectRequest.ProtoReflect.Descriptor instead.
func (*ImportProjectRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{10}
}

func (x *ImportProjectRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *ImportProjectRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ImportProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportProjectRequest) GetImportProject() *ProjectOwnerAndSlug {
	if x != nil {
		return x.ImportProject
	}
	return nil
}

func (x *ImportProjectRequest) GetImportProjects() []*ProjectOwnerAndSlug {
	if x != nil {
		return x.ImportProjects
	}
	return nil
}

type UnImportProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	UnimportOwner string                 `protobuf:"bytes,3,opt,name=unimport_owner,json=unimportOwner,proto3" json:"unimport_owner,omitempty"`
	UnimportSlug  string                 `protobuf:"bytes,4,opt,name=unimport_slug,json=unimportSlug,proto3" json:"unimport_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnImportProjectRequest) Reset() {
	*x = UnImportProjectRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnImportProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnImportProjectRequest) ProtoMessage() {}

func (x *UnImportProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnImportProjectRequest.ProtoReflect.Descriptor instead.
func (*UnImportProjectRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{11}
}

func (x *UnImportProjectRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *UnImportProjectRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UnImportProjectRequest) GetUnimportOwner() string {
	if x != nil {
		return x.UnimportOwner
	}
	return ""
}

func (x *UnImportProjectRequest) GetUnimportSlug() string {
	if x != nil {
		return x.UnimportSlug
	}
	return ""
}

type ImportProjectResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Imports       []*protos.ImportedProject `protobuf:"bytes,1,rep,name=imports,proto3" json:"imports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProjectResponse) Reset() {
	*x = ImportProjectResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProjectResponse) ProtoMessage() {}

func (x *ImportProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProjectResponse.ProtoReflect.Descriptor instead.
func (*ImportProjectResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{12}
}

func (x *ImportProjectResponse) GetImports() []*protos.ImportedProject {
	if x != nil {
		return x.Imports
	}
	return nil
}

type SearchProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectRequest) Reset() {
	*x = SearchProjectRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectRequest) ProtoMessage() {}

func (x *SearchProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectRequest.ProtoReflect.Descriptor instead.
func (*SearchProjectRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchProjectRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type SearchProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*protos.ProjectInfo  `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectResponse) Reset() {
	*x = SearchProjectResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectResponse) ProtoMessage() {}

func (x *SearchProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectResponse.ProtoReflect.Descriptor instead.
func (*SearchProjectResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{14}
}

func (x *SearchProjectResponse) GetProjects() []*protos.ProjectInfo {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*protos.Project      `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectsResponse) Reset() {
	*x = ProjectsResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsResponse) ProtoMessage() {}

func (x *ProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsResponse.ProtoReflect.Descriptor instead.
func (*ProjectsResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{15}
}

func (x *ProjectsResponse) GetProjects() []*protos.Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectsInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*protos.ProjectInfo  `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectsInfoResponse) Reset() {
	*x = ProjectsInfoResponse{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsInfoResponse) ProtoMessage() {}

func (x *ProjectsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsInfoResponse.ProtoReflect.Descriptor instead.
func (*ProjectsInfoResponse) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{16}
}

func (x *ProjectsInfoResponse) GetProjects() []*protos.ProjectInfo {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectVariableKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectVariableKey) Reset() {
	*x = ProjectVariableKey{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectVariableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectVariableKey) ProtoMessage() {}

func (x *ProjectVariableKey) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectVariableKey.ProtoReflect.Descriptor instead.
func (*ProjectVariableKey) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{17}
}

func (x *ProjectVariableKey) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectVariableKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CloneProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TargetProject:
	//
	//	*CloneProjectRequest_ProjectId
	//	*CloneProjectRequest_Project
	TargetProject isCloneProjectRequest_TargetProject `protobuf_oneof:"target_project"`
	FromProjectId string                              `protobuf:"bytes,3,opt,name=from_project_id,json=fromProjectId,proto3" json:"from_project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneProjectRequest) Reset() {
	*x = CloneProjectRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneProjectRequest) ProtoMessage() {}

func (x *CloneProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneProjectRequest.ProtoReflect.Descriptor instead.
func (*CloneProjectRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{18}
}

func (x *CloneProjectRequest) GetTargetProject() isCloneProjectRequest_TargetProject {
	if x != nil {
		return x.TargetProject
	}
	return nil
}

func (x *CloneProjectRequest) GetProjectId() string {
	if x != nil {
		if x, ok := x.TargetProject.(*CloneProjectRequest_ProjectId); ok {
			return x.ProjectId
		}
	}
	return ""
}

func (x *CloneProjectRequest) GetProject() *protos.Project {
	if x != nil {
		if x, ok := x.TargetProject.(*CloneProjectRequest_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *CloneProjectRequest) GetFromProjectId() string {
	if x != nil {
		return x.FromProjectId
	}
	return ""
}

type isCloneProjectRequest_TargetProject interface {
	isCloneProjectRequest_TargetProject()
}

type CloneProjectRequest_ProjectId struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3,oneof"`
}

type CloneProjectRequest_Project struct {
	Project *protos.Project `protobuf:"bytes,2,opt,name=project,proto3,oneof"`
}

func (*CloneProjectRequest_ProjectId) isCloneProjectRequest_TargetProject() {}

func (*CloneProjectRequest_Project) isCloneProjectRequest_TargetProject() {}

type TransferProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ToOwnerName   string                 `protobuf:"bytes,2,opt,name=to_owner_name,json=toOwnerName,proto3" json:"to_owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferProjectRequest) Reset() {
	*x = TransferProjectRequest{}
	mi := &file_service_project_protos_project_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProjectRequest) ProtoMessage() {}

func (x *TransferProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_project_protos_project_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProjectRequest.ProtoReflect.Descriptor instead.
func (*TransferProjectRequest) Descriptor() ([]byte, []int) {
	return file_service_project_protos_project_service_proto_rawDescGZIP(), []int{19}
}

func (x *TransferProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TransferProjectRequest) GetToOwnerName() string {
	if x != nil {
		return x.ToOwnerName
	}
	return ""
}

var File_service_project_protos_project_service_proto protoreflect.FileDescriptor

const file_service_project_protos_project_service_proto_rawDesc = "" +
	"\n" +
	",service/project/protos/project_service.proto\x12\x0fproject_service\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\"service/common/protos/common.proto\"6\n" +
	"\x15GetProjectByIdRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"u\n" +
	"\x12GetProjectResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.common.ProjectR\aproject\x124\n" +
	"\vpermissions\x18\x02 \x03(\x0e2\x12.common.PermissionR\vpermissions\"g\n" +
	"\x13ProjectOwnerAndSlug\x12-\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tB\x0e\x92A\v\xca>\b\xfa\x02\x05ownerR\townerName\x12!\n" +
	"\x04slug\x18\x02 \x01(\tB\r\x92A\n" +
	"\xca>\a\xfa\x02\x04slugR\x04slug\"2\n" +
	"\x11CheckOwnerRequest\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tR\townerName\"E\n" +
	"\rCheckResponse\x12\x19\n" +
	"\bis_taken\x18\x01 \x01(\bR\aisTaken\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\"Y\n" +
	"\x15GetProjectListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\xb3\x01\n" +
	"\x16GetProjectListResponse\x12+\n" +
	"\bprojects\x18\x01 \x03(\v2\x0f.common.ProjectR\bprojects\x128\n" +
	"\x0fshared_projects\x18\x02 \x03(\v2\x0f.common.ProjectR\x0esharedProjects\x122\n" +
	"\forg_projects\x18\x03 \x03(\v2\x0f.common.ProjectR\vorgProjects\"a\n" +
	"\x14ProjectMemberRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12*\n" +
	"\x11username_or_email\x18\x02 \x01(\tR\x0fusernameOrEmail\"P\n" +
	"\x15ProjectMemberResponse\x127\n" +
	"\amembers\x18\x01 \x03(\v2\x1d.common.Project.ProjectMemberR\amembers\"_\n" +
	"\x13ProjectViewResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12)\n" +
	"\x05views\x18\x02 \x03(\v2\x13.common.ProjectViewR\x05views\"\x98\x02\n" +
	"\x14ImportProjectRequest\x12-\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tB\x0e\x92A\v\xca>\b\xfa\x02\x05ownerR\townerName\x12!\n" +
	"\x04slug\x18\x02 \x01(\tB\r\x92A\n" +
	"\xca>\a\xfa\x02\x04slugR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12K\n" +
	"\x0eimport_project\x18\x04 \x01(\v2$.project_service.ProjectOwnerAndSlugR\rimportProject\x12M\n" +
	"\x0fimport_projects\x18\x05 \x03(\v2$.project_service.ProjectOwnerAndSlugR\x0eimportProjects\"\xb6\x01\n" +
	"\x16UnImportProjectRequest\x12-\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tB\x0e\x92A\v\xca>\b\xfa\x02\x05ownerR\townerName\x12!\n" +
	"\x04slug\x18\x02 \x01(\tB\r\x92A\n" +
	"\xca>\a\xfa\x02\x04slugR\x04slug\x12%\n" +
	"\x0eunimport_owner\x18\x03 \x01(\tR\runimportOwner\x12#\n" +
	"\runimport_slug\x18\x04 \x01(\tR\funimportSlug\"J\n" +
	"\x15ImportProjectResponse\x121\n" +
	"\aimports\x18\x01 \x03(\v2\x17.common.ImportedProjectR\aimports\"$\n" +
	"\x14SearchProjectRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\"H\n" +
	"\x15SearchProjectResponse\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.common.ProjectInfoR\bprojects\"?\n" +
	"\x10ProjectsResponse\x12+\n" +
	"\bprojects\x18\x01 \x03(\v2\x0f.common.ProjectR\bprojects\"G\n" +
	"\x14ProjectsInfoResponse\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.common.ProjectInfoR\bprojects\"E\n" +
	"\x12ProjectVariableKey\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x9d\x01\n" +
	"\x13CloneProjectRequest\x12\x1f\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tH\x00R\tprojectId\x12+\n" +
	"\aproject\x18\x02 \x01(\v2\x0f.common.ProjectH\x00R\aproject\x12&\n" +
	"\x0ffrom_project_id\x18\x03 \x01(\tR\rfromProjectIdB\x10\n" +
	"\x0etarget_project\"[\n" +
	"\x16TransferProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\"\n" +
	"\rto_owner_name\x18\x02 \x01(\tR\vtoOwnerName2\xd8\x1f\n" +
	"\x0eProjectService\x12\x9b\x01\n" +
	"\n" +
	"GetProject\x12$.project_service.ProjectOwnerAndSlug\x1a#.project_service.GetProjectResponse\"B\x92A\x00\x92\xb5\x18\x10\n" +
	"\fproject:read\x18\x01\x82\xd3\xe4\x93\x02%\x12#/api/v1/project/{owner_name}/{slug}\x12\x8a\x01\n" +
	"\x0eGetProjectById\x12&.project_service.GetProjectByIdRequest\x1a\x13.common.ProjectInfo\";\x92A\x00\x92\xb5\x18\x10\n" +
	"\fproject:read\x18\x01\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/project/{project_id}\x12~\n" +
	"\x0eGetProjectList\x12&.project_service.GetProjectListRequest\x1a'.project_service.GetProjectListResponse\"\x1b\x92A\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/projects\x12\x9f\x01\n" +
	"\x16GetPopulateProjectList\x12&.project_service.GetProjectListRequest\x1a'.project_service.GetProjectListResponse\"4\x92A\x00\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/populate-projects\x12\\\n" +
	"\vSaveProject\x12\x0f.common.Project\x1a\x0f.common.Project\"+\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/projects\x12\x92\x01\n" +
	"\rDeleteProject\x12&.project_service.GetProjectByIdRequest\x1a\x0f.common.Project\"H\x92\xb5\x18\x0f\n" +
	"\rproject:admin\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/projects/{project_id}\x12\xb2\x01\n" +
	"\fCloneProject\x12$.project_service.CloneProjectRequest\x1a\x0f.common.Project\"k\x92A\x00\x92\xb5\x183\n" +
	"\fproject:read\x12#\n" +
	"\x10project_id_field\x12\x0ffrom_project_id\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/projects/clone\x12\xa6\x01\n" +
	"\x14TransferProjectOwner\x12'.project_service.TransferProjectRequest\x1a\x0f.common.Project\"T\x92\xb5\x18\x0f\n" +
	"\rproject:admin\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/projects/{project_id}/transfer\x12\xb6\x01\n" +
	"\x10AddProjectMember\x12%.project_service.ProjectMemberRequest\x1a&.project_service.ProjectMemberResponse\"S\x92\xb5\x18\x0f\n" +
	"\rproject:admin\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/projects/{project_id}/members\x12\xb7\x01\n" +
	"\x13RemoveProjectMember\x12%.project_service.ProjectMemberRequest\x1a&.project_service.ProjectMemberResponse\"Q\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02;*9/api/v1/projects/{project_id}/members/{username_or_email}\x12\xa1\x01\n" +
	"\x0eCheckProjectId\x12$.project_service.ProjectOwnerAndSlug\x1a\x1e.project_service.CheckResponse\"I\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x023\x121/api/v1/projects/{owner_name}/{slug}/availability\x12\x9c\x01\n" +
	"\x0eAddProjectView\x12\x13.common.ProjectView\x1a$.project_service.ProjectViewResponse\"O\x92\xb5\x18\x0f\n" +
	"\rproject:write\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/project_view/{project_id}\x12\xa1\x01\n" +
	"\x11RemoveProjectView\x12\x13.common.ProjectView\x1a$.project_service.ProjectViewResponse\"Q\x92\xb5\x18\x0f\n" +
	"\rproject:admin\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02(*&/api/v1/project_view/{project_id}/{id}\x12\xa4\x01\n" +
	"\x11UpdateProjectView\x12\x13.common.ProjectView\x1a$.project_service.ProjectViewResponse\"T\x92\xb5\x18\x0f\n" +
	"\rproject:admin\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/project_view/{project_id}/{id}\x12\x95\x01\n" +
	"\rSearchProject\x12%.project_service.SearchProjectRequest\x1a&.project_service.SearchProjectResponse\"5\x92\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/projects/search\x12\xb3\x01\n" +
	"\rImportProject\x12%.project_service.ImportProjectRequest\x1a&.project_service.ImportProjectResponse\"S\x92A\x00\x92\xb5\x18\x0f\n" +
	"\rproject:write\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/project/{owner_name}/{slug}/importprojects\x12\xd7\x01\n" +
	"\x0fUnImportProject\x12'.project_service.UnImportProjectRequest\x1a&.project_service.ImportProjectResponse\"s\x92A\x00\x92\xb5\x18\x0f\n" +
	"\rproject:write\x82\xd3\xe4\x93\x02W*U/api/v1/project/{owner_name}/{slug}/unimportprojects/{unimport_owner}/{unimport_slug}\x12\xb3\x01\n" +
	"\x12GetImportedProject\x12$.project_service.ProjectOwnerAndSlug\x1a&.project_service.ImportProjectResponse\"O\x92A\x00\x92\xb5\x18\x0e\n" +
	"\fproject:read\x82\xd3\xe4\x93\x024\x122/api/v1/project/{owner_name}/{slug}/importprojects\x12\x81\x01\n" +
	"\x12GetStarredProjects\x12\x16.google.protobuf.Empty\x1a!.project_service.ProjectsResponse\"0\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/starred_projects\x12\x9e\x01\n" +
	"\vStarProject\x12&.project_service.GetProjectByIdRequest\x1a\x16.google.protobuf.Empty\"O\x92\xb5\x18\x0e\n" +
	"\fproject:read\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02'\"%/api/v1/starred_projects/{project_id}\x12\x8e\x01\n" +
	"\rUnstarProject\x12&.project_service.GetProjectByIdRequest\x1a\x16.google.protobuf.Empty\"=\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02'*%/api/v1/starred_projects/{project_id}\x12\x83\x01\n" +
	"\x11GetViewedProjects\x12\x16.google.protobuf.Empty\x1a%.project_service.ProjectsInfoResponse\"/\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/viewed_projects\x12\xaa\x01\n" +
	"\x13GetProjectVariables\x12&.project_service.GetProjectByIdRequest\x1a\x18.common.ProjectVariables\"Q\x92\xb5\x18\x0e\n" +
	"\fproject:read\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02)\x12'/api/v1/projects/{project_id}/variables\x12\x9f\x01\n" +
	"\x14SaveProjectVariables\x12\x18.common.ProjectVariables\x1a\x16.google.protobuf.Empty\"U\x92\xb5\x18\x0f\n" +
	"\rproject:write\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02,:\x01*\"'/api/v1/projects/{project_id}/variables\x12\xaf\x01\n" +
	"\x16DeleteProjectVariables\x12#.project_service.ProjectVariableKey\x1a\x16.google.protobuf.Empty\"X\x92\xb5\x18\x0f\n" +
	"\rproject:write\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02/*-/api/v1/projects/{project_id}/variables/{key}\x1a\f\x92A\t\n" +
	"\aProjectB.Z,sentioxyz/sentio-core/service/project/protosb\x06proto3"

var (
	file_service_project_protos_project_service_proto_rawDescOnce sync.Once
	file_service_project_protos_project_service_proto_rawDescData []byte
)

func file_service_project_protos_project_service_proto_rawDescGZIP() []byte {
	file_service_project_protos_project_service_proto_rawDescOnce.Do(func() {
		file_service_project_protos_project_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_project_protos_project_service_proto_rawDesc), len(file_service_project_protos_project_service_proto_rawDesc)))
	})
	return file_service_project_protos_project_service_proto_rawDescData
}

var file_service_project_protos_project_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_service_project_protos_project_service_proto_goTypes = []any{
	(*GetProjectByIdRequest)(nil),        // 0: project_service.GetProjectByIdRequest
	(*GetProjectResponse)(nil),           // 1: project_service.GetProjectResponse
	(*ProjectOwnerAndSlug)(nil),          // 2: project_service.ProjectOwnerAndSlug
	(*CheckOwnerRequest)(nil),            // 3: project_service.CheckOwnerRequest
	(*CheckResponse)(nil),                // 4: project_service.CheckResponse
	(*GetProjectListRequest)(nil),        // 5: project_service.GetProjectListRequest
	(*GetProjectListResponse)(nil),       // 6: project_service.GetProjectListResponse
	(*ProjectMemberRequest)(nil),         // 7: project_service.ProjectMemberRequest
	(*ProjectMemberResponse)(nil),        // 8: project_service.ProjectMemberResponse
	(*ProjectViewResponse)(nil),          // 9: project_service.ProjectViewResponse
	(*ImportProjectRequest)(nil),         // 10: project_service.ImportProjectRequest
	(*UnImportProjectRequest)(nil),       // 11: project_service.UnImportProjectRequest
	(*ImportProjectResponse)(nil),        // 12: project_service.ImportProjectResponse
	(*SearchProjectRequest)(nil),         // 13: project_service.SearchProjectRequest
	(*SearchProjectResponse)(nil),        // 14: project_service.SearchProjectResponse
	(*ProjectsResponse)(nil),             // 15: project_service.ProjectsResponse
	(*ProjectsInfoResponse)(nil),         // 16: project_service.ProjectsInfoResponse
	(*ProjectVariableKey)(nil),           // 17: project_service.ProjectVariableKey
	(*CloneProjectRequest)(nil),          // 18: project_service.CloneProjectRequest
	(*TransferProjectRequest)(nil),       // 19: project_service.TransferProjectRequest
	(*protos.Project)(nil),               // 20: common.Project
	(protos.Permission)(0),               // 21: common.Permission
	(*protos.Project_ProjectMember)(nil), // 22: common.Project.ProjectMember
	(*protos.ProjectView)(nil),           // 23: common.ProjectView
	(*protos.ImportedProject)(nil),       // 24: common.ImportedProject
	(*protos.ProjectInfo)(nil),           // 25: common.ProjectInfo
	(*emptypb.Empty)(nil),                // 26: google.protobuf.Empty
	(*protos.ProjectVariables)(nil),      // 27: common.ProjectVariables
}
var file_service_project_protos_project_service_proto_depIdxs = []int32{
	20, // 0: project_service.GetProjectResponse.project:type_name -> common.Project
	21, // 1: project_service.GetProjectResponse.permissions:type_name -> common.Permission
	20, // 2: project_service.GetProjectListResponse.projects:type_name -> common.Project
	20, // 3: project_service.GetProjectListResponse.shared_projects:type_name -> common.Project
	20, // 4: project_service.GetProjectListResponse.org_projects:type_name -> common.Project
	22, // 5: project_service.ProjectMemberResponse.members:type_name -> common.Project.ProjectMember
	23, // 6: project_service.ProjectViewResponse.views:type_name -> common.ProjectView
	2,  // 7: project_service.ImportProjectRequest.import_project:type_name -> project_service.ProjectOwnerAndSlug
	2,  // 8: project_service.ImportProjectRequest.import_projects:type_name -> project_service.ProjectOwnerAndSlug
	24, // 9: project_service.ImportProjectResponse.imports:type_name -> common.ImportedProject
	25, // 10: project_service.SearchProjectResponse.projects:type_name -> common.ProjectInfo
	20, // 11: project_service.ProjectsResponse.projects:type_name -> common.Project
	25, // 12: project_service.ProjectsInfoResponse.projects:type_name -> common.ProjectInfo
	20, // 13: project_service.CloneProjectRequest.project:type_name -> common.Project
	2,  // 14: project_service.ProjectService.GetProject:input_type -> project_service.ProjectOwnerAndSlug
	0,  // 15: project_service.ProjectService.GetProjectById:input_type -> project_service.GetProjectByIdRequest
	5,  // 16: project_service.ProjectService.GetProjectList:input_type -> project_service.GetProjectListRequest
	5,  // 17: project_service.ProjectService.GetPopulateProjectList:input_type -> project_service.GetProjectListRequest
	20, // 18: project_service.ProjectService.SaveProject:input_type -> common.Project
	0,  // 19: project_service.ProjectService.DeleteProject:input_type -> project_service.GetProjectByIdRequest
	18, // 20: project_service.ProjectService.CloneProject:input_type -> project_service.CloneProjectRequest
	19, // 21: project_service.ProjectService.TransferProjectOwner:input_type -> project_service.TransferProjectRequest
	7,  // 22: project_service.ProjectService.AddProjectMember:input_type -> project_service.ProjectMemberRequest
	7,  // 23: project_service.ProjectService.RemoveProjectMember:input_type -> project_service.ProjectMemberRequest
	2,  // 24: project_service.ProjectService.CheckProjectId:input_type -> project_service.ProjectOwnerAndSlug
	23, // 25: project_service.ProjectService.AddProjectView:input_type -> common.ProjectView
	23, // 26: project_service.ProjectService.RemoveProjectView:input_type -> common.ProjectView
	23, // 27: project_service.ProjectService.UpdateProjectView:input_type -> common.ProjectView
	13, // 28: project_service.ProjectService.SearchProject:input_type -> project_service.SearchProjectRequest
	10, // 29: project_service.ProjectService.ImportProject:input_type -> project_service.ImportProjectRequest
	11, // 30: project_service.ProjectService.UnImportProject:input_type -> project_service.UnImportProjectRequest
	2,  // 31: project_service.ProjectService.GetImportedProject:input_type -> project_service.ProjectOwnerAndSlug
	26, // 32: project_service.ProjectService.GetStarredProjects:input_type -> google.protobuf.Empty
	0,  // 33: project_service.ProjectService.StarProject:input_type -> project_service.GetProjectByIdRequest
	0,  // 34: project_service.ProjectService.UnstarProject:input_type -> project_service.GetProjectByIdRequest
	26, // 35: project_service.ProjectService.GetViewedProjects:input_type -> google.protobuf.Empty
	0,  // 36: project_service.ProjectService.GetProjectVariables:input_type -> project_service.GetProjectByIdRequest
	27, // 37: project_service.ProjectService.SaveProjectVariables:input_type -> common.ProjectVariables
	17, // 38: project_service.ProjectService.DeleteProjectVariables:input_type -> project_service.ProjectVariableKey
	1,  // 39: project_service.ProjectService.GetProject:output_type -> project_service.GetProjectResponse
	25, // 40: project_service.ProjectService.GetProjectById:output_type -> common.ProjectInfo
	6,  // 41: project_service.ProjectService.GetProjectList:output_type -> project_service.GetProjectListResponse
	6,  // 42: project_service.ProjectService.GetPopulateProjectList:output_type -> project_service.GetProjectListResponse
	20, // 43: project_service.ProjectService.SaveProject:output_type -> common.Project
	20, // 44: project_service.ProjectService.DeleteProject:output_type -> common.Project
	20, // 45: project_service.ProjectService.CloneProject:output_type -> common.Project
	20, // 46: project_service.ProjectService.TransferProjectOwner:output_type -> common.Project
	8,  // 47: project_service.ProjectService.AddProjectMember:output_type -> project_service.ProjectMemberResponse
	8,  // 48: project_service.ProjectService.RemoveProjectMember:output_type -> project_service.ProjectMemberResponse
	4,  // 49: project_service.ProjectService.CheckProjectId:output_type -> project_service.CheckResponse
	9,  // 50: project_service.ProjectService.AddProjectView:output_type -> project_service.ProjectViewResponse
	9,  // 51: project_service.ProjectService.RemoveProjectView:output_type -> project_service.ProjectViewResponse
	9,  // 52: project_service.ProjectService.UpdateProjectView:output_type -> project_service.ProjectViewResponse
	14, // 53: project_service.ProjectService.SearchProject:output_type -> project_service.SearchProjectResponse
	12, // 54: project_service.ProjectService.ImportProject:output_type -> project_service.ImportProjectResponse
	12, // 55: project_service.ProjectService.UnImportProject:output_type -> project_service.ImportProjectResponse
	12, // 56: project_service.ProjectService.GetImportedProject:output_type -> project_service.ImportProjectResponse
	15, // 57: project_service.ProjectService.GetStarredProjects:output_type -> project_service.ProjectsResponse
	26, // 58: project_service.ProjectService.StarProject:output_type -> google.protobuf.Empty
	26, // 59: project_service.ProjectService.UnstarProject:output_type -> google.protobuf.Empty
	16, // 60: project_service.ProjectService.GetViewedProjects:output_type -> project_service.ProjectsInfoResponse
	27, // 61: project_service.ProjectService.GetProjectVariables:output_type -> common.ProjectVariables
	26, // 62: project_service.ProjectService.SaveProjectVariables:output_type -> google.protobuf.Empty
	26, // 63: project_service.ProjectService.DeleteProjectVariables:output_type -> google.protobuf.Empty
	39, // [39:64] is the sub-list for method output_type
	14, // [14:39] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_service_project_protos_project_service_proto_init() }
func file_service_project_protos_project_service_proto_init() {
	if File_service_project_protos_project_service_proto != nil {
		return
	}
	file_service_project_protos_project_service_proto_msgTypes[18].OneofWrappers = []any{
		(*CloneProjectRequest_ProjectId)(nil),
		(*CloneProjectRequest_Project)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_project_protos_project_service_proto_rawDesc), len(file_service_project_protos_project_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_project_protos_project_service_proto_goTypes,
		DependencyIndexes: file_service_project_protos_project_service_proto_depIdxs,
		MessageInfos:      file_service_project_protos_project_service_proto_msgTypes,
	}.Build()
	File_service_project_protos_project_service_proto = out.File
	file_service_project_protos_project_service_proto_goTypes = nil
	file_service_project_protos_project_service_proto_depIdxs = nil
}
