// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: service/formula/protos/formula_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FormulaService_Evaluate_FullMethodName = "/formula_service.FormulaService/Evaluate"
)

// FormulaServiceClient is the client API for FormulaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormulaServiceClient interface {
	Evaluate(ctx context.Context, in *FormulaRequest, opts ...grpc.CallOption) (*FormulaResponse, error)
}

type formulaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFormulaServiceClient(cc grpc.ClientConnInterface) FormulaServiceClient {
	return &formulaServiceClient{cc}
}

func (c *formulaServiceClient) Evaluate(ctx context.Context, in *FormulaRequest, opts ...grpc.CallOption) (*FormulaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FormulaResponse)
	err := c.cc.Invoke(ctx, FormulaService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormulaServiceServer is the server API for FormulaService service.
// All implementations must embed UnimplementedFormulaServiceServer
// for forward compatibility.
type FormulaServiceServer interface {
	Evaluate(context.Context, *FormulaRequest) (*FormulaResponse, error)
	mustEmbedUnimplementedFormulaServiceServer()
}

// UnimplementedFormulaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFormulaServiceServer struct{}

func (UnimplementedFormulaServiceServer) Evaluate(context.Context, *FormulaRequest) (*FormulaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedFormulaServiceServer) mustEmbedUnimplementedFormulaServiceServer() {}
func (UnimplementedFormulaServiceServer) testEmbeddedByValue()                        {}

// UnsafeFormulaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormulaServiceServer will
// result in compilation errors.
type UnsafeFormulaServiceServer interface {
	mustEmbedUnimplementedFormulaServiceServer()
}

func RegisterFormulaServiceServer(s grpc.ServiceRegistrar, srv FormulaServiceServer) {
	// If the following call pancis, it indicates UnimplementedFormulaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FormulaService_ServiceDesc, srv)
}

func _FormulaService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormulaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormulaServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormulaService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormulaServiceServer).Evaluate(ctx, req.(*FormulaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormulaService_ServiceDesc is the grpc.ServiceDesc for FormulaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormulaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "formula_service.FormulaService",
	HandlerType: (*FormulaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _FormulaService_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/formula/protos/formula_service.proto",
}
