// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js,keep_empty_files=true"
// @generated from file bazel/protoc-gen-es/tests/protos/internal_only.proto (package estest.hidden, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file bazel/protoc-gen-es/tests/protos/internal_only.proto.
 */
export const file_bazel_protoc_gen_es_tests_protos_internal_only: GenFile = /*@__PURE__*/
  fileDesc("CjRiYXplbC9wcm90b2MtZ2VuLWVzL3Rlc3RzL3Byb3Rvcy9pbnRlcm5hbF9vbmx5LnByb3RvEg1lc3Rlc3QuaGlkZGVuYgZwcm90bzM");

