// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js,keep_empty_files=true"
// @generated from file bazel/protoc-gen-es/tests/protos/public_service.proto (package estest, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Shared } from "./dep_pb.js";
import { file_bazel_protoc_gen_es_tests_protos_dep } from "./dep_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bazel/protoc-gen-es/tests/protos/public_service.proto.
 */
export const file_bazel_protoc_gen_es_tests_protos_public_service: GenFile = /*@__PURE__*/
  fileDesc("CjViYXplbC9wcm90b2MtZ2VuLWVzL3Rlc3RzL3Byb3Rvcy9wdWJsaWNfc2VydmljZS5wcm90bxIGZXN0ZXN0ItEBCg9HZXRUaGluZ1JlcXVlc3QSCgoCaWQYASABKAkSDgoEbmFtZRgDIAEoCUgAEhMKBmxvY2FsZRgGIAEoCUgBiAEBEjMKBmxhYmVscxgHIAMoCzIjLmVzdGVzdC5HZXRUaGluZ1JlcXVlc3QuTGFiZWxzRW50cnkaQQoLTGFiZWxzRW50cnkSCwoDa2V5GAEgASgJEiEKBXZhbHVlGAIgASgLMhIuZXN0ZXN0LmRlcC5TaGFyZWQ6AjgBQgoKCHNlbGVjdG9yQgkKB19sb2NhbGUihgEKBVRoaW5nEgoKAmlkGAEgASgJEhoKBGtpbmQYAiABKA4yDC5lc3Rlc3QuS2luZBIdCgZwYXJlbnQYAyABKAsyDS5lc3Rlc3QuVGhpbmcSIAoEbWV0YRgEIAEoCzISLmVzdGVzdC5UaGluZy5NZXRhGhQKBE1ldGESDAoEZXRhZxgBIAEoCSosCgRLaW5kEhQKEEtJTkRfVU5TUEVDSUZJRUQQABIOCgpLSU5EX0JBU0lDEAEyWAoJUHVibGljQXBpEksKCEdldFRoaW5nEhcuZXN0ZXN0LkdldFRoaW5nUmVxdWVzdBoNLmVzdGVzdC5UaGluZyIXgtPkkwIREg8vdjEvdGhpbmdzL3tpZH1iBnByb3RvMw", [file_bazel_protoc_gen_es_tests_protos_dep]);

/**
 * @generated from message estest.GetThingRequest
 */
export type GetThingRequest = Message<"estest.GetThingRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from oneof estest.GetThingRequest.selector
   */
  selector: {
    /**
     * @generated from field: string name = 3;
     */
    value: string;
    case: "name";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional string locale = 6;
   */
  locale?: string | undefined;

  /**
   * @generated from field: map<string, estest.dep.Shared> labels = 7;
   */
  labels: { [key: string]: Shared };
};

/**
 * Describes the message estest.GetThingRequest.
 * Use `create(GetThingRequestSchema)` to create a new message.
 */
export const GetThingRequestSchema: GenMessage<GetThingRequest> = /*@__PURE__*/
  messageDesc(file_bazel_protoc_gen_es_tests_protos_public_service, 0);

/**
 * @generated from message estest.Thing
 */
export type Thing = Message<"estest.Thing"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: estest.Kind kind = 2;
   */
  kind: Kind;

  /**
   * @generated from field: estest.Thing parent = 3;
   */
  parent?: Thing | undefined;

  /**
   * @generated from field: estest.Thing.Meta meta = 4;
   */
  meta?: Thing_Meta | undefined;
};

/**
 * Describes the message estest.Thing.
 * Use `create(ThingSchema)` to create a new message.
 */
export const ThingSchema: GenMessage<Thing> = /*@__PURE__*/
  messageDesc(file_bazel_protoc_gen_es_tests_protos_public_service, 1);

/**
 * @generated from message estest.Thing.Meta
 */
export type Thing_Meta = Message<"estest.Thing.Meta"> & {
  /**
   * @generated from field: string etag = 1;
   */
  etag: string;
};

/**
 * Describes the message estest.Thing.Meta.
 * Use `create(Thing_MetaSchema)` to create a new message.
 */
export const Thing_MetaSchema: GenMessage<Thing_Meta> = /*@__PURE__*/
  messageDesc(file_bazel_protoc_gen_es_tests_protos_public_service, 1, 0);

/**
 * @generated from enum estest.Kind
 */
export enum Kind {
  /**
   * @generated from enum value: KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: KIND_BASIC = 1;
   */
  BASIC = 1,
}

/**
 * Describes the enum estest.Kind.
 */
export const KindSchema: GenEnum<Kind> = /*@__PURE__*/
  enumDesc(file_bazel_protoc_gen_es_tests_protos_public_service, 0);

/**
 * @generated from service estest.PublicApi
 */
export const PublicApi: GenService<{
  /**
   * @generated from rpc estest.PublicApi.GetThing
   */
  getThing: {
    methodKind: "unary";
    input: typeof GetThingRequestSchema;
    output: typeof ThingSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bazel_protoc_gen_es_tests_protos_public_service, 0);

