// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: service/observability/protos/observability_service.proto

package protos

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	protos "sentioxyz/sentio-core/service/common/protos"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetricsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectId        string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version          int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	LabelLimit       uint64                 `protobuf:"varint,4,opt,name=label_limit,json=labelLimit,proto3" json:"label_limit,omitempty"`
	LabelSearchQuery string                 `protobuf:"bytes,5,opt,name=label_search_query,json=labelSearchQuery,proto3" json:"label_search_query,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetricsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetMetricsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMetricsRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetMetricsRequest) GetLabelLimit() uint64 {
	if x != nil {
		return x.LabelLimit
	}
	return 0
}

func (x *GetMetricsRequest) GetLabelSearchQuery() string {
	if x != nil {
		return x.LabelSearchQuery
	}
	return ""
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricInfo          `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ComputeStats  *protos.ComputeStats   `protobuf:"bytes,2,opt,name=compute_stats,json=computeStats,proto3" json:"compute_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsResponse) GetMetrics() []*MetricInfo {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetMetricsResponse) GetComputeStats() *protos.ComputeStats {
	if x != nil {
		return x.ComputeStats
	}
	return nil
}

type MetricInfo struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	Name            string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName     string                             `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ProjectId       string                             `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ContractName    []string                           `protobuf:"bytes,4,rep,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	ContractAddress []string                           `protobuf:"bytes,5,rep,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ChainId         []string                           `protobuf:"bytes,6,rep,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Labels          map[string]*MetricInfo_LabelValues `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata        *MetricMetadata                    `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricInfo) Reset() {
	*x = MetricInfo{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricInfo) ProtoMessage() {}

func (x *MetricInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricInfo.ProtoReflect.Descriptor instead.
func (*MetricInfo) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{2}
}

func (x *MetricInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MetricInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *MetricInfo) GetContractName() []string {
	if x != nil {
		return x.ContractName
	}
	return nil
}

func (x *MetricInfo) GetContractAddress() []string {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *MetricInfo) GetChainId() []string {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *MetricInfo) GetLabels() map[string]*MetricInfo_LabelValues {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricInfo) GetMetadata() *MetricMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetricMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Help          string                 `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricMetadata) Reset() {
	*x = MetricMetadata{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricMetadata) ProtoMessage() {}

func (x *MetricMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricMetadata.ProtoReflect.Descriptor instead.
func (*MetricMetadata) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{3}
}

func (x *MetricMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricMetadata) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricMetadata) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MetricMetadata) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type QueryRangeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProjectOwner string                 `protobuf:"bytes,1,opt,name=project_owner,json=projectOwner,proto3" json:"project_owner,omitempty"`
	ProjectSlug  string                 `protobuf:"bytes,2,opt,name=project_slug,json=projectSlug,proto3" json:"project_slug,omitempty"`
	Queries      []*protos.Query        `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	// Deprecated: Marked as deprecated in service/observability/protos/observability_service.proto.
	Formulas                   []*protos.Formula     `protobuf:"bytes,4,rep,name=formulas,proto3" json:"formulas,omitempty"`
	SamplesLimit               int32                 `protobuf:"varint,5,opt,name=samples_limit,json=samplesLimit,proto3" json:"samples_limit,omitempty"`
	TimeRange                  *protos.TimeRangeLite `protobuf:"bytes,6,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	ProjectId                  string                `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Version                    int32                 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	SamplesOffset              int32                 `protobuf:"varint,9,opt,name=samples_offset,json=samplesOffset,proto3" json:"samples_offset,omitempty"`
	EnableExperimentalFeatures bool                  `protobuf:"varint,10,opt,name=enable_experimental_features,json=enableExperimentalFeatures,proto3" json:"enable_experimental_features,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *QueryRangeRequest) Reset() {
	*x = QueryRangeRequest{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRangeRequest) ProtoMessage() {}

func (x *QueryRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRangeRequest.ProtoReflect.Descriptor instead.
func (*QueryRangeRequest) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRangeRequest) GetProjectOwner() string {
	if x != nil {
		return x.ProjectOwner
	}
	return ""
}

func (x *QueryRangeRequest) GetProjectSlug() string {
	if x != nil {
		return x.ProjectSlug
	}
	return ""
}

func (x *QueryRangeRequest) GetQueries() []*protos.Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

// Deprecated: Marked as deprecated in service/observability/protos/observability_service.proto.
func (x *QueryRangeRequest) GetFormulas() []*protos.Formula {
	if x != nil {
		return x.Formulas
	}
	return nil
}

func (x *QueryRangeRequest) GetSamplesLimit() int32 {
	if x != nil {
		return x.SamplesLimit
	}
	return 0
}

func (x *QueryRangeRequest) GetTimeRange() *protos.TimeRangeLite {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *QueryRangeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *QueryRangeRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryRangeRequest) GetSamplesOffset() int32 {
	if x != nil {
		return x.SamplesOffset
	}
	return 0
}

func (x *QueryRangeRequest) GetEnableExperimentalFeatures() bool {
	if x != nil {
		return x.EnableExperimentalFeatures
	}
	return false
}

type QueryValueRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ProjectOwner               string                 `protobuf:"bytes,1,opt,name=project_owner,json=projectOwner,proto3" json:"project_owner,omitempty"`
	ProjectSlug                string                 `protobuf:"bytes,2,opt,name=project_slug,json=projectSlug,proto3" json:"project_slug,omitempty"`
	Queries                    []*protos.Query        `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	Formulas                   []*protos.Formula      `protobuf:"bytes,4,rep,name=formulas,proto3" json:"formulas,omitempty"`
	Time                       string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	SamplesLimit               int32                  `protobuf:"varint,6,opt,name=samples_limit,json=samplesLimit,proto3" json:"samples_limit,omitempty"`
	Version                    int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Timezone                   string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SamplesOffset              int32                  `protobuf:"varint,9,opt,name=samples_offset,json=samplesOffset,proto3" json:"samples_offset,omitempty"`
	EnableExperimentalFeatures bool                   `protobuf:"varint,10,opt,name=enable_experimental_features,json=enableExperimentalFeatures,proto3" json:"enable_experimental_features,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *QueryValueRequest) Reset() {
	*x = QueryValueRequest{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValueRequest) ProtoMessage() {}

func (x *QueryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValueRequest.ProtoReflect.Descriptor instead.
func (*QueryValueRequest) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{5}
}

func (x *QueryValueRequest) GetProjectOwner() string {
	if x != nil {
		return x.ProjectOwner
	}
	return ""
}

func (x *QueryValueRequest) GetProjectSlug() string {
	if x != nil {
		return x.ProjectSlug
	}
	return ""
}

func (x *QueryValueRequest) GetQueries() []*protos.Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *QueryValueRequest) GetFormulas() []*protos.Formula {
	if x != nil {
		return x.Formulas
	}
	return nil
}

func (x *QueryValueRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *QueryValueRequest) GetSamplesLimit() int32 {
	if x != nil {
		return x.SamplesLimit
	}
	return 0
}

func (x *QueryValueRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryValueRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *QueryValueRequest) GetSamplesOffset() int32 {
	if x != nil {
		return x.SamplesOffset
	}
	return 0
}

func (x *QueryValueRequest) GetEnableExperimentalFeatures() bool {
	if x != nil {
		return x.EnableExperimentalFeatures
	}
	return false
}

type QueryValueResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       []*QueryValueResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryValueResponse) Reset() {
	*x = QueryValueResponse{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValueResponse) ProtoMessage() {}

func (x *QueryValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValueResponse.ProtoReflect.Descriptor instead.
func (*QueryValueResponse) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{6}
}

func (x *QueryValueResponse) GetResults() []*QueryValueResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type MetricsQueryResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Results       []*MetricsQueryResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryResponse) Reset() {
	*x = MetricsQueryResponse{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse) ProtoMessage() {}

func (x *MetricsQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsQueryResponse) GetResults() []*MetricsQueryResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type Series struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId       string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Contract        string                 `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	DisplayName     string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ContractAddress string                 `protobuf:"bytes,5,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{8}
}

func (x *Series) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Series) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Series) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *Series) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Series) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *Series) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricInfo_LabelValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricInfo_LabelValues) Reset() {
	*x = MetricInfo_LabelValues{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricInfo_LabelValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricInfo_LabelValues) ProtoMessage() {}

func (x *MetricInfo_LabelValues) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricInfo_LabelValues.ProtoReflect.Descriptor instead.
func (*MetricInfo_LabelValues) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MetricInfo_LabelValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *MetricInfo_LabelValues) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type QueryValueResponse_Result struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Sample        []*MetricsQueryResponse_Sample `protobuf:"bytes,1,rep,name=sample,proto3" json:"sample,omitempty"`
	Error         string                         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Alias         string                         `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Id            string                         `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Color         string                         `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryValueResponse_Result) Reset() {
	*x = QueryValueResponse_Result{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValueResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValueResponse_Result) ProtoMessage() {}

func (x *QueryValueResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValueResponse_Result.ProtoReflect.Descriptor instead.
func (*QueryValueResponse_Result) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *QueryValueResponse_Result) GetSample() []*MetricsQueryResponse_Sample {
	if x != nil {
		return x.Sample
	}
	return nil
}

func (x *QueryValueResponse_Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryValueResponse_Result) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *QueryValueResponse_Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryValueResponse_Result) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type MetricsQueryResponse_Matrix struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Samples       []*MetricsQueryResponse_Sample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	TotalSamples  int32                          `protobuf:"varint,2,opt,name=total_samples,json=totalSamples,proto3" json:"total_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryResponse_Matrix) Reset() {
	*x = MetricsQueryResponse_Matrix{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse_Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse_Matrix) ProtoMessage() {}

func (x *MetricsQueryResponse_Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse_Matrix.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse_Matrix) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *MetricsQueryResponse_Matrix) GetSamples() []*MetricsQueryResponse_Sample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *MetricsQueryResponse_Matrix) GetTotalSamples() int32 {
	if x != nil {
		return x.TotalSamples
	}
	return 0
}

type MetricsQueryResponse_Sample struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Metric        *MetricsQueryResponse_Metric  `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Values        []*MetricsQueryResponse_Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryResponse_Sample) Reset() {
	*x = MetricsQueryResponse_Sample{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse_Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse_Sample) ProtoMessage() {}

func (x *MetricsQueryResponse_Sample) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse_Sample.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse_Sample) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{7, 1}
}

func (x *MetricsQueryResponse_Sample) GetMetric() *MetricsQueryResponse_Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *MetricsQueryResponse_Sample) GetValues() []*MetricsQueryResponse_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type MetricsQueryResponse_Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryResponse_Metric) Reset() {
	*x = MetricsQueryResponse_Metric{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse_Metric) ProtoMessage() {}

func (x *MetricsQueryResponse_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse_Metric.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse_Metric) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{7, 2}
}

func (x *MetricsQueryResponse_Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricsQueryResponse_Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricsQueryResponse_Metric) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type MetricsQueryResponse_Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ExtraValues   []float64              `protobuf:"fixed64,3,rep,packed,name=extra_values,json=extraValues,proto3" json:"extra_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsQueryResponse_Value) Reset() {
	*x = MetricsQueryResponse_Value{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse_Value) ProtoMessage() {}

func (x *MetricsQueryResponse_Value) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse_Value.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse_Value) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{7, 3}
}

func (x *MetricsQueryResponse_Value) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsQueryResponse_Value) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricsQueryResponse_Value) GetExtraValues() []float64 {
	if x != nil {
		return x.ExtraValues
	}
	return nil
}

type MetricsQueryResponse_Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MetricsQueryResponseType:
	//
	//	*MetricsQueryResponse_Result_Matrix
	//	*MetricsQueryResponse_Result_Error
	MetricsQueryResponseType isMetricsQueryResponse_Result_MetricsQueryResponseType `protobuf_oneof:"metrics_query_response_type"`
	Alias                    string                                                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Id                       string                                                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	ComputeStats             *protos.ComputeStats                                   `protobuf:"bytes,5,opt,name=compute_stats,json=computeStats,proto3" json:"compute_stats,omitempty"`
	Color                    string                                                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MetricsQueryResponse_Result) Reset() {
	*x = MetricsQueryResponse_Result{}
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsQueryResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsQueryResponse_Result) ProtoMessage() {}

func (x *MetricsQueryResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_observability_protos_observability_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsQueryResponse_Result.ProtoReflect.Descriptor instead.
func (*MetricsQueryResponse_Result) Descriptor() ([]byte, []int) {
	return file_service_observability_protos_observability_service_proto_rawDescGZIP(), []int{7, 4}
}

func (x *MetricsQueryResponse_Result) GetMetricsQueryResponseType() isMetricsQueryResponse_Result_MetricsQueryResponseType {
	if x != nil {
		return x.MetricsQueryResponseType
	}
	return nil
}

func (x *MetricsQueryResponse_Result) GetMatrix() *MetricsQueryResponse_Matrix {
	if x != nil {
		if x, ok := x.MetricsQueryResponseType.(*MetricsQueryResponse_Result_Matrix); ok {
			return x.Matrix
		}
	}
	return nil
}

func (x *MetricsQueryResponse_Result) GetError() string {
	if x != nil {
		if x, ok := x.MetricsQueryResponseType.(*MetricsQueryResponse_Result_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *MetricsQueryResponse_Result) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *MetricsQueryResponse_Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricsQueryResponse_Result) GetComputeStats() *protos.ComputeStats {
	if x != nil {
		return x.ComputeStats
	}
	return nil
}

func (x *MetricsQueryResponse_Result) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type isMetricsQueryResponse_Result_MetricsQueryResponseType interface {
	isMetricsQueryResponse_Result_MetricsQueryResponseType()
}

type MetricsQueryResponse_Result_Matrix struct {
	Matrix *MetricsQueryResponse_Matrix `protobuf:"bytes,1,opt,name=matrix,proto3,oneof"`
}

type MetricsQueryResponse_Result_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*MetricsQueryResponse_Result_Matrix) isMetricsQueryResponse_Result_MetricsQueryResponseType() {}

func (*MetricsQueryResponse_Result_Error) isMetricsQueryResponse_Result_MetricsQueryResponseType() {}

var File_service_observability_protos_observability_service_proto protoreflect.FileDescriptor

const file_service_observability_protos_observability_service_proto_rawDesc = "" +
	"\n" +
	"8service/observability/protos/observability_service.proto\x12\x0fmetrics_service\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\"service/common/protos/common.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xaf\x01\n" +
	"\x11GetMetricsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x1f\n" +
	"\vlabel_limit\x18\x04 \x01(\x04R\n" +
	"labelLimit\x12,\n" +
	"\x12label_search_query\x18\x05 \x01(\tR\x10labelSearchQuery\"\x86\x01\n" +
	"\x12GetMetricsResponse\x125\n" +
	"\ametrics\x18\x01 \x03(\v2\x1b.metrics_service.MetricInfoR\ametrics\x129\n" +
	"\rcompute_stats\x18\x02 \x01(\v2\x14.common.ComputeStatsR\fcomputeStats\"\xf7\x03\n" +
	"\n" +
	"MetricInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12#\n" +
	"\rcontract_name\x18\x04 \x03(\tR\fcontractName\x12)\n" +
	"\x10contract_address\x18\x05 \x03(\tR\x0fcontractAddress\x12\x19\n" +
	"\bchain_id\x18\x06 \x03(\tR\achainId\x12?\n" +
	"\x06labels\x18\a \x03(\v2'.metrics_service.MetricInfo.LabelsEntryR\x06labels\x12;\n" +
	"\bmetadata\x18\b \x01(\v2\x1f.metrics_service.MetricMetadataR\bmetadata\x1aF\n" +
	"\vLabelValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x1ab\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.metrics_service.MetricInfo.LabelValuesR\x05value:\x028\x01\"i\n" +
	"\x0eMetricMetadata\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x12\n" +
	"\x04help\x18\x03 \x01(\tR\x04help\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\"\xf6\a\n" +
	"\x11QueryRangeRequest\x123\n" +
	"\rproject_owner\x18\x01 \x01(\tB\x0e\x92A\v\xca>\b\xfa\x02\x05ownerR\fprojectOwner\x120\n" +
	"\fproject_slug\x18\x02 \x01(\tB\r\x92A\n" +
	"\xca>\a\xfa\x02\x04slugR\vprojectSlug\x12'\n" +
	"\aqueries\x18\x03 \x03(\v2\r.common.QueryR\aqueries\x12/\n" +
	"\bformulas\x18\x04 \x03(\v2\x0f.common.FormulaB\x02\x18\x01R\bformulas\x12#\n" +
	"\rsamples_limit\x18\x05 \x01(\x05R\fsamplesLimit\x129\n" +
	"\n" +
	"time_range\x18\x06 \x01(\v2\x15.common.TimeRangeLiteB\x03\xe0A\x02R\ttimeRange\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x12%\n" +
	"\x0esamples_offset\x18\t \x01(\x05R\rsamplesOffset\x12@\n" +
	"\x1cenable_experimental_features\x18\n" +
	" \x01(\bR\x1aenableExperimentalFeatures:\x9d\x04\x92A\x99\x042\x96\x04{\"queries\":[{\"query\":\"mint_sum\",\"alias\":\"Mint (24 hours)\",\"id\":\"a\",\"labelSelector\":{},\"aggregate\":null,\"functions\":[{\"name\":\"rollup_sum\",\"arguments\":[{\"durationValue\":{\"value\":1,\"unit\":\"d\"}}]}],\"disabled\":false},{\"query\":\"burn_sum\",\"alias\":\"Burn (24 hours)\",\"id\":\"b\",\"labelSelector\":{},\"aggregate\":null,\"functions\":[{\"name\":\"rollup_sum\",\"arguments\":[{\"durationValue\":{\"value\":1,\"unit\":\"d\"}}]}],\"disabled\":false}],\"formulas\":[],\"timeRange\":{\"start\":\"now-30d\",\"end\":\"now\",\"step\":3600,\"timezone\":\"America/Los_Angeles\"},\"samplesLimit\":20}\"\xa8\x03\n" +
	"\x11QueryValueRequest\x123\n" +
	"\rproject_owner\x18\x01 \x01(\tB\x0e\x92A\v\xca>\b\xfa\x02\x05ownerR\fprojectOwner\x120\n" +
	"\fproject_slug\x18\x02 \x01(\tB\r\x92A\n" +
	"\xca>\a\xfa\x02\x04slugR\vprojectSlug\x12'\n" +
	"\aqueries\x18\x03 \x03(\v2\r.common.QueryR\aqueries\x12+\n" +
	"\bformulas\x18\x04 \x03(\v2\x0f.common.FormulaR\bformulas\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\x12#\n" +
	"\rsamples_limit\x18\x06 \x01(\x05R\fsamplesLimit\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12%\n" +
	"\x0esamples_offset\x18\t \x01(\x05R\rsamplesOffset\x12@\n" +
	"\x1cenable_experimental_features\x18\n" +
	" \x01(\bR\x1aenableExperimentalFeatures\"\xfd\x01\n" +
	"\x12QueryValueResponse\x12D\n" +
	"\aresults\x18\x01 \x03(\v2*.metrics_service.QueryValueResponse.ResultR\aresults\x1a\xa0\x01\n" +
	"\x06Result\x12D\n" +
	"\x06sample\x18\x01 \x03(\v2,.metrics_service.MetricsQueryResponse.SampleR\x06sample\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"\x9b\a\n" +
	"\x14MetricsQueryResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.metrics_service.MetricsQueryResponse.ResultR\aresults\x1au\n" +
	"\x06Matrix\x12F\n" +
	"\asamples\x18\x01 \x03(\v2,.metrics_service.MetricsQueryResponse.SampleR\asamples\x12#\n" +
	"\rtotal_samples\x18\x02 \x01(\x05R\ftotalSamples\x1a\x93\x01\n" +
	"\x06Sample\x12D\n" +
	"\x06metric\x18\x01 \x01(\v2,.metrics_service.MetricsQueryResponse.MetricR\x06metric\x12C\n" +
	"\x06values\x18\x02 \x03(\v2+.metrics_service.MetricsQueryResponse.ValueR\x06values\x1a\xcc\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12P\n" +
	"\x06labels\x18\x02 \x03(\v28.metrics_service.MetricsQueryResponse.Metric.LabelsEntryR\x06labels\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a^\n" +
	"\x05Value\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12!\n" +
	"\fextra_values\x18\x03 \x03(\x01R\vextraValues\x1a\xfe\x01\n" +
	"\x06Result\x12F\n" +
	"\x06matrix\x18\x01 \x01(\v2,.metrics_service.MetricsQueryResponse.MatrixH\x00R\x06matrix\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x129\n" +
	"\rcompute_stats\x18\x05 \x01(\v2\x14.common.ComputeStatsR\fcomputeStats\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05colorB\x1d\n" +
	"\x1bmetrics_query_response_type\"\x9d\x02\n" +
	"\x06Series\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1a\n" +
	"\bcontract\x18\x03 \x01(\tR\bcontract\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12)\n" +
	"\x10contract_address\x18\x05 \x01(\tR\x0fcontractAddress\x12;\n" +
	"\x06labels\x18\x06 \x03(\v2#.metrics_service.Series.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdb\x04\n" +
	"\x14ObservabilityService\x12\x85\x01\n" +
	"\n" +
	"GetMetrics\x12\".metrics_service.GetMetricsRequest\x1a#.metrics_service.GetMetricsResponse\".\x92A\x00\x92\xb5\x18\x10\n" +
	"\fproject:read\x18\x01\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/metrics\x12\xd5\x01\n" +
	"\n" +
	"QueryRange\x12\".metrics_service.QueryRangeRequest\x1a%.metrics_service.MetricsQueryResponse\"|\x92A\x00\x82\xb5\x18\x1c\n" +
	"\vapi_metrics\x12\rwebui_metrics\x92\xb5\x18\x10\n" +
	"\fproject:read\x18\x01\x82\xd3\xe4\x93\x02?:\x01*\":/api/v1/metrics/{project_owner}/{project_slug}/query_range\x12\xd7\x01\n" +
	"\x05Query\x12\".metrics_service.QueryValueRequest\x1a#.metrics_service.QueryValueResponse\"\x84\x01\x92A\x0e*\fQueryInstant\x82\xb5\x18\x1c\n" +
	"\vapi_metrics\x12\rwebui_metrics\x92\xb5\x18\x10\n" +
	"\fproject:read\x18\x01\x82\xd3\xe4\x93\x029:\x01*\"4/api/v1/metrics/{project_owner}/{project_slug}/query\x1a\t\x92A\x06\n" +
	"\x04DataB4Z2sentioxyz/sentio-core/service/observability/protosb\x06proto3"

var (
	file_service_observability_protos_observability_service_proto_rawDescOnce sync.Once
	file_service_observability_protos_observability_service_proto_rawDescData []byte
)

func file_service_observability_protos_observability_service_proto_rawDescGZIP() []byte {
	file_service_observability_protos_observability_service_proto_rawDescOnce.Do(func() {
		file_service_observability_protos_observability_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_observability_protos_observability_service_proto_rawDesc), len(file_service_observability_protos_observability_service_proto_rawDesc)))
	})
	return file_service_observability_protos_observability_service_proto_rawDescData
}

var file_service_observability_protos_observability_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_service_observability_protos_observability_service_proto_goTypes = []any{
	(*GetMetricsRequest)(nil),           // 0: metrics_service.GetMetricsRequest
	(*GetMetricsResponse)(nil),          // 1: metrics_service.GetMetricsResponse
	(*MetricInfo)(nil),                  // 2: metrics_service.MetricInfo
	(*MetricMetadata)(nil),              // 3: metrics_service.MetricMetadata
	(*QueryRangeRequest)(nil),           // 4: metrics_service.QueryRangeRequest
	(*QueryValueRequest)(nil),           // 5: metrics_service.QueryValueRequest
	(*QueryValueResponse)(nil),          // 6: metrics_service.QueryValueResponse
	(*MetricsQueryResponse)(nil),        // 7: metrics_service.MetricsQueryResponse
	(*Series)(nil),                      // 8: metrics_service.Series
	(*MetricInfo_LabelValues)(nil),      // 9: metrics_service.MetricInfo.LabelValues
	nil,                                 // 10: metrics_service.MetricInfo.LabelsEntry
	(*QueryValueResponse_Result)(nil),   // 11: metrics_service.QueryValueResponse.Result
	(*MetricsQueryResponse_Matrix)(nil), // 12: metrics_service.MetricsQueryResponse.Matrix
	(*MetricsQueryResponse_Sample)(nil), // 13: metrics_service.MetricsQueryResponse.Sample
	(*MetricsQueryResponse_Metric)(nil), // 14: metrics_service.MetricsQueryResponse.Metric
	(*MetricsQueryResponse_Value)(nil),  // 15: metrics_service.MetricsQueryResponse.Value
	(*MetricsQueryResponse_Result)(nil), // 16: metrics_service.MetricsQueryResponse.Result
	nil,                                 // 17: metrics_service.MetricsQueryResponse.Metric.LabelsEntry
	nil,                                 // 18: metrics_service.Series.LabelsEntry
	(*protos.ComputeStats)(nil),         // 19: common.ComputeStats
	(*protos.Query)(nil),                // 20: common.Query
	(*protos.Formula)(nil),              // 21: common.Formula
	(*protos.TimeRangeLite)(nil),        // 22: common.TimeRangeLite
}
var file_service_observability_protos_observability_service_proto_depIdxs = []int32{
	2,  // 0: metrics_service.GetMetricsResponse.metrics:type_name -> metrics_service.MetricInfo
	19, // 1: metrics_service.GetMetricsResponse.compute_stats:type_name -> common.ComputeStats
	10, // 2: metrics_service.MetricInfo.labels:type_name -> metrics_service.MetricInfo.LabelsEntry
	3,  // 3: metrics_service.MetricInfo.metadata:type_name -> metrics_service.MetricMetadata
	20, // 4: metrics_service.QueryRangeRequest.queries:type_name -> common.Query
	21, // 5: metrics_service.QueryRangeRequest.formulas:type_name -> common.Formula
	22, // 6: metrics_service.QueryRangeRequest.time_range:type_name -> common.TimeRangeLite
	20, // 7: metrics_service.QueryValueRequest.queries:type_name -> common.Query
	21, // 8: metrics_service.QueryValueRequest.formulas:type_name -> common.Formula
	11, // 9: metrics_service.QueryValueResponse.results:type_name -> metrics_service.QueryValueResponse.Result
	16, // 10: metrics_service.MetricsQueryResponse.results:type_name -> metrics_service.MetricsQueryResponse.Result
	18, // 11: metrics_service.Series.labels:type_name -> metrics_service.Series.LabelsEntry
	9,  // 12: metrics_service.MetricInfo.LabelsEntry.value:type_name -> metrics_service.MetricInfo.LabelValues
	13, // 13: metrics_service.QueryValueResponse.Result.sample:type_name -> metrics_service.MetricsQueryResponse.Sample
	13, // 14: metrics_service.MetricsQueryResponse.Matrix.samples:type_name -> metrics_service.MetricsQueryResponse.Sample
	14, // 15: metrics_service.MetricsQueryResponse.Sample.metric:type_name -> metrics_service.MetricsQueryResponse.Metric
	15, // 16: metrics_service.MetricsQueryResponse.Sample.values:type_name -> metrics_service.MetricsQueryResponse.Value
	17, // 17: metrics_service.MetricsQueryResponse.Metric.labels:type_name -> metrics_service.MetricsQueryResponse.Metric.LabelsEntry
	12, // 18: metrics_service.MetricsQueryResponse.Result.matrix:type_name -> metrics_service.MetricsQueryResponse.Matrix
	19, // 19: metrics_service.MetricsQueryResponse.Result.compute_stats:type_name -> common.ComputeStats
	0,  // 20: metrics_service.ObservabilityService.GetMetrics:input_type -> metrics_service.GetMetricsRequest
	4,  // 21: metrics_service.ObservabilityService.QueryRange:input_type -> metrics_service.QueryRangeRequest
	5,  // 22: metrics_service.ObservabilityService.Query:input_type -> metrics_service.QueryValueRequest
	1,  // 23: metrics_service.ObservabilityService.GetMetrics:output_type -> metrics_service.GetMetricsResponse
	7,  // 24: metrics_service.ObservabilityService.QueryRange:output_type -> metrics_service.MetricsQueryResponse
	6,  // 25: metrics_service.ObservabilityService.Query:output_type -> metrics_service.QueryValueResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_service_observability_protos_observability_service_proto_init() }
func file_service_observability_protos_observability_service_proto_init() {
	if File_service_observability_protos_observability_service_proto != nil {
		return
	}
	file_service_observability_protos_observability_service_proto_msgTypes[16].OneofWrappers = []any{
		(*MetricsQueryResponse_Result_Matrix)(nil),
		(*MetricsQueryResponse_Result_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_observability_protos_observability_service_proto_rawDesc), len(file_service_observability_protos_observability_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_observability_protos_observability_service_proto_goTypes,
		DependencyIndexes: file_service_observability_protos_observability_service_proto_depIdxs,
		MessageInfos:      file_service_observability_protos_observability_service_proto_msgTypes,
	}.Build()
	File_service_observability_protos_observability_service_proto = out.File
	file_service_observability_protos_observability_service_proto_goTypes = nil
	file_service_observability_protos_observability_service_proto_depIdxs = nil
}
