// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: service/usage/protos/manager.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsageService_AsyncSave_FullMethodName              = "/usage_service.UsageService/AsyncSave"
	UsageService_CheckOverLimit_FullMethodName         = "/usage_service.UsageService/CheckOverLimit"
	UsageService_Statistic_FullMethodName              = "/usage_service.UsageService/Statistic"
	UsageService_CheckOverLimitExt_FullMethodName      = "/usage_service.UsageService/CheckOverLimitExt"
	UsageService_StatisticExt_FullMethodName           = "/usage_service.UsageService/StatisticExt"
	UsageService_StatisticAdmin_FullMethodName         = "/usage_service.UsageService/StatisticAdmin"
	UsageService_Ranking_FullMethodName                = "/usage_service.UsageService/Ranking"
	UsageService_RankingAdmin_FullMethodName           = "/usage_service.UsageService/RankingAdmin"
	UsageService_ListSkuCostConfigAdmin_FullMethodName = "/usage_service.UsageService/ListSkuCostConfigAdmin"
	UsageService_SetSkuCostAdmin_FullMethodName        = "/usage_service.UsageService/SetSkuCostAdmin"
	UsageService_DelSkuCostAdmin_FullMethodName        = "/usage_service.UsageService/DelSkuCostAdmin"
	UsageService_ListSKU_FullMethodName                = "/usage_service.UsageService/ListSKU"
	UsageService_UpdateSKUMetaAdmin_FullMethodName     = "/usage_service.UsageService/UpdateSKUMetaAdmin"
)

// UsageServiceClient is the client API for UsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsageServiceClient interface {
	AsyncSave(ctx context.Context, in *AsyncSaveRequest, opts ...grpc.CallOption) (*AsyncSaveResponse, error)
	CheckOverLimit(ctx context.Context, in *CheckOverLimitRequest, opts ...grpc.CallOption) (*CheckOverLimitResponse, error)
	Statistic(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error)
	CheckOverLimitExt(ctx context.Context, in *CheckOverLimitExtRequest, opts ...grpc.CallOption) (*CheckOverLimitResponse, error)
	StatisticExt(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error)
	StatisticAdmin(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error)
	Ranking(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*StatisticResponse, error)
	RankingAdmin(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*StatisticResponse, error)
	ListSkuCostConfigAdmin(ctx context.Context, in *ListSkuCostConfigRequest, opts ...grpc.CallOption) (*ListSkuCostConfigResponse, error)
	SetSkuCostAdmin(ctx context.Context, in *SetSkuCostRequest, opts ...grpc.CallOption) (*SetSkuCostResponse, error)
	DelSkuCostAdmin(ctx context.Context, in *DelSkuCostRequest, opts ...grpc.CallOption) (*DelSkuCostResponse, error)
	ListSKU(ctx context.Context, in *ListSKURequest, opts ...grpc.CallOption) (*ListSKUResponse, error)
	UpdateSKUMetaAdmin(ctx context.Context, in *UpdateSKUMetaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type usageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageServiceClient(cc grpc.ClientConnInterface) UsageServiceClient {
	return &usageServiceClient{cc}
}

func (c *usageServiceClient) AsyncSave(ctx context.Context, in *AsyncSaveRequest, opts ...grpc.CallOption) (*AsyncSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsyncSaveResponse)
	err := c.cc.Invoke(ctx, UsageService_AsyncSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) CheckOverLimit(ctx context.Context, in *CheckOverLimitRequest, opts ...grpc.CallOption) (*CheckOverLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOverLimitResponse)
	err := c.cc.Invoke(ctx, UsageService_CheckOverLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) Statistic(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticResponse)
	err := c.cc.Invoke(ctx, UsageService_Statistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) CheckOverLimitExt(ctx context.Context, in *CheckOverLimitExtRequest, opts ...grpc.CallOption) (*CheckOverLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOverLimitResponse)
	err := c.cc.Invoke(ctx, UsageService_CheckOverLimitExt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) StatisticExt(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticResponse)
	err := c.cc.Invoke(ctx, UsageService_StatisticExt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) StatisticAdmin(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticResponse)
	err := c.cc.Invoke(ctx, UsageService_StatisticAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) Ranking(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*StatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticResponse)
	err := c.cc.Invoke(ctx, UsageService_Ranking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) RankingAdmin(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*StatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticResponse)
	err := c.cc.Invoke(ctx, UsageService_RankingAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) ListSkuCostConfigAdmin(ctx context.Context, in *ListSkuCostConfigRequest, opts ...grpc.CallOption) (*ListSkuCostConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkuCostConfigResponse)
	err := c.cc.Invoke(ctx, UsageService_ListSkuCostConfigAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) SetSkuCostAdmin(ctx context.Context, in *SetSkuCostRequest, opts ...grpc.CallOption) (*SetSkuCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSkuCostResponse)
	err := c.cc.Invoke(ctx, UsageService_SetSkuCostAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) DelSkuCostAdmin(ctx context.Context, in *DelSkuCostRequest, opts ...grpc.CallOption) (*DelSkuCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelSkuCostResponse)
	err := c.cc.Invoke(ctx, UsageService_DelSkuCostAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) ListSKU(ctx context.Context, in *ListSKURequest, opts ...grpc.CallOption) (*ListSKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSKUResponse)
	err := c.cc.Invoke(ctx, UsageService_ListSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usageServiceClient) UpdateSKUMetaAdmin(ctx context.Context, in *UpdateSKUMetaRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UsageService_UpdateSKUMetaAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsageServiceServer is the server API for UsageService service.
// All implementations must embed UnimplementedUsageServiceServer
// for forward compatibility.
type UsageServiceServer interface {
	AsyncSave(context.Context, *AsyncSaveRequest) (*AsyncSaveResponse, error)
	CheckOverLimit(context.Context, *CheckOverLimitRequest) (*CheckOverLimitResponse, error)
	Statistic(context.Context, *StatisticRequest) (*StatisticResponse, error)
	CheckOverLimitExt(context.Context, *CheckOverLimitExtRequest) (*CheckOverLimitResponse, error)
	StatisticExt(context.Context, *StatisticRequest) (*StatisticResponse, error)
	StatisticAdmin(context.Context, *StatisticRequest) (*StatisticResponse, error)
	Ranking(context.Context, *RankingRequest) (*StatisticResponse, error)
	RankingAdmin(context.Context, *RankingRequest) (*StatisticResponse, error)
	ListSkuCostConfigAdmin(context.Context, *ListSkuCostConfigRequest) (*ListSkuCostConfigResponse, error)
	SetSkuCostAdmin(context.Context, *SetSkuCostRequest) (*SetSkuCostResponse, error)
	DelSkuCostAdmin(context.Context, *DelSkuCostRequest) (*DelSkuCostResponse, error)
	ListSKU(context.Context, *ListSKURequest) (*ListSKUResponse, error)
	UpdateSKUMetaAdmin(context.Context, *UpdateSKUMetaRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUsageServiceServer()
}

// UnimplementedUsageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsageServiceServer struct{}

func (UnimplementedUsageServiceServer) AsyncSave(context.Context, *AsyncSaveRequest) (*AsyncSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsyncSave not implemented")
}
func (UnimplementedUsageServiceServer) CheckOverLimit(context.Context, *CheckOverLimitRequest) (*CheckOverLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckOverLimit not implemented")
}
func (UnimplementedUsageServiceServer) Statistic(context.Context, *StatisticRequest) (*StatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Statistic not implemented")
}
func (UnimplementedUsageServiceServer) CheckOverLimitExt(context.Context, *CheckOverLimitExtRequest) (*CheckOverLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckOverLimitExt not implemented")
}
func (UnimplementedUsageServiceServer) StatisticExt(context.Context, *StatisticRequest) (*StatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatisticExt not implemented")
}
func (UnimplementedUsageServiceServer) StatisticAdmin(context.Context, *StatisticRequest) (*StatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatisticAdmin not implemented")
}
func (UnimplementedUsageServiceServer) Ranking(context.Context, *RankingRequest) (*StatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ranking not implemented")
}
func (UnimplementedUsageServiceServer) RankingAdmin(context.Context, *RankingRequest) (*StatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RankingAdmin not implemented")
}
func (UnimplementedUsageServiceServer) ListSkuCostConfigAdmin(context.Context, *ListSkuCostConfigRequest) (*ListSkuCostConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkuCostConfigAdmin not implemented")
}
func (UnimplementedUsageServiceServer) SetSkuCostAdmin(context.Context, *SetSkuCostRequest) (*SetSkuCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSkuCostAdmin not implemented")
}
func (UnimplementedUsageServiceServer) DelSkuCostAdmin(context.Context, *DelSkuCostRequest) (*DelSkuCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelSkuCostAdmin not implemented")
}
func (UnimplementedUsageServiceServer) ListSKU(context.Context, *ListSKURequest) (*ListSKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSKU not implemented")
}
func (UnimplementedUsageServiceServer) UpdateSKUMetaAdmin(context.Context, *UpdateSKUMetaRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSKUMetaAdmin not implemented")
}
func (UnimplementedUsageServiceServer) mustEmbedUnimplementedUsageServiceServer() {}
func (UnimplementedUsageServiceServer) testEmbeddedByValue()                      {}

// UnsafeUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageServiceServer will
// result in compilation errors.
type UnsafeUsageServiceServer interface {
	mustEmbedUnimplementedUsageServiceServer()
}

func RegisterUsageServiceServer(s grpc.ServiceRegistrar, srv UsageServiceServer) {
	// If the following call pancis, it indicates UnimplementedUsageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsageService_ServiceDesc, srv)
}

func _UsageService_AsyncSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsyncSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).AsyncSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_AsyncSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).AsyncSave(ctx, req.(*AsyncSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_CheckOverLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOverLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).CheckOverLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_CheckOverLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).CheckOverLimit(ctx, req.(*CheckOverLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_Statistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).Statistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_Statistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).Statistic(ctx, req.(*StatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_CheckOverLimitExt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOverLimitExtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).CheckOverLimitExt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_CheckOverLimitExt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).CheckOverLimitExt(ctx, req.(*CheckOverLimitExtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_StatisticExt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).StatisticExt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_StatisticExt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).StatisticExt(ctx, req.(*StatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_StatisticAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).StatisticAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_StatisticAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).StatisticAdmin(ctx, req.(*StatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_Ranking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).Ranking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_Ranking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).Ranking(ctx, req.(*RankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_RankingAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).RankingAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_RankingAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).RankingAdmin(ctx, req.(*RankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_ListSkuCostConfigAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkuCostConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).ListSkuCostConfigAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_ListSkuCostConfigAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).ListSkuCostConfigAdmin(ctx, req.(*ListSkuCostConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_SetSkuCostAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSkuCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).SetSkuCostAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_SetSkuCostAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).SetSkuCostAdmin(ctx, req.(*SetSkuCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_DelSkuCostAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelSkuCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).DelSkuCostAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_DelSkuCostAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).DelSkuCostAdmin(ctx, req.(*DelSkuCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_ListSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).ListSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_ListSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).ListSKU(ctx, req.(*ListSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsageService_UpdateSKUMetaAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSKUMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServiceServer).UpdateSKUMetaAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageService_UpdateSKUMetaAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServiceServer).UpdateSKUMetaAdmin(ctx, req.(*UpdateSKUMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsageService_ServiceDesc is the grpc.ServiceDesc for UsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usage_service.UsageService",
	HandlerType: (*UsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AsyncSave",
			Handler:    _UsageService_AsyncSave_Handler,
		},
		{
			MethodName: "CheckOverLimit",
			Handler:    _UsageService_CheckOverLimit_Handler,
		},
		{
			MethodName: "Statistic",
			Handler:    _UsageService_Statistic_Handler,
		},
		{
			MethodName: "CheckOverLimitExt",
			Handler:    _UsageService_CheckOverLimitExt_Handler,
		},
		{
			MethodName: "StatisticExt",
			Handler:    _UsageService_StatisticExt_Handler,
		},
		{
			MethodName: "StatisticAdmin",
			Handler:    _UsageService_StatisticAdmin_Handler,
		},
		{
			MethodName: "Ranking",
			Handler:    _UsageService_Ranking_Handler,
		},
		{
			MethodName: "RankingAdmin",
			Handler:    _UsageService_RankingAdmin_Handler,
		},
		{
			MethodName: "ListSkuCostConfigAdmin",
			Handler:    _UsageService_ListSkuCostConfigAdmin_Handler,
		},
		{
			MethodName: "SetSkuCostAdmin",
			Handler:    _UsageService_SetSkuCostAdmin_Handler,
		},
		{
			MethodName: "DelSkuCostAdmin",
			Handler:    _UsageService_DelSkuCostAdmin_Handler,
		},
		{
			MethodName: "ListSKU",
			Handler:    _UsageService_ListSKU_Handler,
		},
		{
			MethodName: "UpdateSKUMetaAdmin",
			Handler:    _UsageService_UpdateSKUMetaAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/usage/protos/manager.proto",
}

const (
	QueryUsageService_CheckQueryBalance_FullMethodName = "/usage_service.QueryUsageService/CheckQueryBalance"
	QueryUsageService_ReportQueryUsage_FullMethodName  = "/usage_service.QueryUsageService/ReportQueryUsage"
)

// QueryUsageServiceClient is the client API for QueryUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryUsageServiceClient interface {
	CheckQueryBalance(ctx context.Context, in *CheckQueryBalanceRequest, opts ...grpc.CallOption) (*CheckQueryBalanceResponse, error)
	ReportQueryUsage(ctx context.Context, in *ReportQueryUsageRequest, opts ...grpc.CallOption) (*ReportQueryUsageResponse, error)
}

type queryUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryUsageServiceClient(cc grpc.ClientConnInterface) QueryUsageServiceClient {
	return &queryUsageServiceClient{cc}
}

func (c *queryUsageServiceClient) CheckQueryBalance(ctx context.Context, in *CheckQueryBalanceRequest, opts ...grpc.CallOption) (*CheckQueryBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckQueryBalanceResponse)
	err := c.cc.Invoke(ctx, QueryUsageService_CheckQueryBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryUsageServiceClient) ReportQueryUsage(ctx context.Context, in *ReportQueryUsageRequest, opts ...grpc.CallOption) (*ReportQueryUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportQueryUsageResponse)
	err := c.cc.Invoke(ctx, QueryUsageService_ReportQueryUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryUsageServiceServer is the server API for QueryUsageService service.
// All implementations must embed UnimplementedQueryUsageServiceServer
// for forward compatibility.
type QueryUsageServiceServer interface {
	CheckQueryBalance(context.Context, *CheckQueryBalanceRequest) (*CheckQueryBalanceResponse, error)
	ReportQueryUsage(context.Context, *ReportQueryUsageRequest) (*ReportQueryUsageResponse, error)
	mustEmbedUnimplementedQueryUsageServiceServer()
}

// UnimplementedQueryUsageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryUsageServiceServer struct{}

func (UnimplementedQueryUsageServiceServer) CheckQueryBalance(context.Context, *CheckQueryBalanceRequest) (*CheckQueryBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckQueryBalance not implemented")
}
func (UnimplementedQueryUsageServiceServer) ReportQueryUsage(context.Context, *ReportQueryUsageRequest) (*ReportQueryUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportQueryUsage not implemented")
}
func (UnimplementedQueryUsageServiceServer) mustEmbedUnimplementedQueryUsageServiceServer() {}
func (UnimplementedQueryUsageServiceServer) testEmbeddedByValue()                           {}

// UnsafeQueryUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryUsageServiceServer will
// result in compilation errors.
type UnsafeQueryUsageServiceServer interface {
	mustEmbedUnimplementedQueryUsageServiceServer()
}

func RegisterQueryUsageServiceServer(s grpc.ServiceRegistrar, srv QueryUsageServiceServer) {
	// If the following call pancis, it indicates UnimplementedQueryUsageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryUsageService_ServiceDesc, srv)
}

func _QueryUsageService_CheckQueryBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckQueryBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryUsageServiceServer).CheckQueryBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryUsageService_CheckQueryBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryUsageServiceServer).CheckQueryBalance(ctx, req.(*CheckQueryBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryUsageService_ReportQueryUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportQueryUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryUsageServiceServer).ReportQueryUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryUsageService_ReportQueryUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryUsageServiceServer).ReportQueryUsage(ctx, req.(*ReportQueryUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryUsageService_ServiceDesc is the grpc.ServiceDesc for QueryUsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryUsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usage_service.QueryUsageService",
	HandlerType: (*QueryUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckQueryBalance",
			Handler:    _QueryUsageService_CheckQueryBalance_Handler,
		},
		{
			MethodName: "ReportQueryUsage",
			Handler:    _QueryUsageService_ReportQueryUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/usage/protos/manager.proto",
}
