// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: service/usage/protos/manager.proto

package protos

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckQueryBalanceRejection int32

const (
	CheckQueryBalanceRejection_UNKNOWN              CheckQueryBalanceRejection = 0
	CheckQueryBalanceRejection_INSUFFICIENT_BALANCE CheckQueryBalanceRejection = 1
	CheckQueryBalanceRejection_UNAUTHORIZED_SIGNER  CheckQueryBalanceRejection = 2
)

// Enum value maps for CheckQueryBalanceRejection.
var (
	CheckQueryBalanceRejection_name = map[int32]string{
		0: "UNKNOWN",
		1: "INSUFFICIENT_BALANCE",
		2: "UNAUTHORIZED_SIGNER",
	}
	CheckQueryBalanceRejection_value = map[string]int32{
		"UNKNOWN":              0,
		"INSUFFICIENT_BALANCE": 1,
		"UNAUTHORIZED_SIGNER":  2,
	}
)

func (x CheckQueryBalanceRejection) Enum() *CheckQueryBalanceRejection {
	p := new(CheckQueryBalanceRejection)
	*p = x
	return p
}

func (x CheckQueryBalanceRejection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckQueryBalanceRejection) Descriptor() protoreflect.EnumDescriptor {
	return file_service_usage_protos_manager_proto_enumTypes[0].Descriptor()
}

func (CheckQueryBalanceRejection) Type() protoreflect.EnumType {
	return &file_service_usage_protos_manager_proto_enumTypes[0]
}

func (x CheckQueryBalanceRejection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckQueryBalanceRejection.Descriptor instead.
func (CheckQueryBalanceRejection) EnumDescriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{0}
}

type CheckOverLimitResponse_Limiter_Category int32

const (
	CheckOverLimitResponse_Limiter_OWNER_LIMITER        CheckOverLimitResponse_Limiter_Category = 0
	CheckOverLimitResponse_Limiter_DEFAULT_TIER_LIMITER CheckOverLimitResponse_Limiter_Category = 1
)

// Enum value maps for CheckOverLimitResponse_Limiter_Category.
var (
	CheckOverLimitResponse_Limiter_Category_name = map[int32]string{
		0: "OWNER_LIMITER",
		1: "DEFAULT_TIER_LIMITER",
	}
	CheckOverLimitResponse_Limiter_Category_value = map[string]int32{
		"OWNER_LIMITER":        0,
		"DEFAULT_TIER_LIMITER": 1,
	}
)

func (x CheckOverLimitResponse_Limiter_Category) Enum() *CheckOverLimitResponse_Limiter_Category {
	p := new(CheckOverLimitResponse_Limiter_Category)
	*p = x
	return p
}

func (x CheckOverLimitResponse_Limiter_Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckOverLimitResponse_Limiter_Category) Descriptor() protoreflect.EnumDescriptor {
	return file_service_usage_protos_manager_proto_enumTypes[1].Descriptor()
}

func (CheckOverLimitResponse_Limiter_Category) Type() protoreflect.EnumType {
	return &file_service_usage_protos_manager_proto_enumTypes[1]
}

func (x CheckOverLimitResponse_Limiter_Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckOverLimitResponse_Limiter_Category.Descriptor instead.
func (CheckOverLimitResponse_Limiter_Category) EnumDescriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{2, 0, 0}
}

type RankingRequest_Target int32

const (
	RankingRequest_OWNER   RankingRequest_Target = 0
	RankingRequest_PROJECT RankingRequest_Target = 1
)

// Enum value maps for RankingRequest_Target.
var (
	RankingRequest_Target_name = map[int32]string{
		0: "OWNER",
		1: "PROJECT",
	}
	RankingRequest_Target_value = map[string]int32{
		"OWNER":   0,
		"PROJECT": 1,
	}
)

func (x RankingRequest_Target) Enum() *RankingRequest_Target {
	p := new(RankingRequest_Target)
	*p = x
	return p
}

func (x RankingRequest_Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankingRequest_Target) Descriptor() protoreflect.EnumDescriptor {
	return file_service_usage_protos_manager_proto_enumTypes[2].Descriptor()
}

func (RankingRequest_Target) Type() protoreflect.EnumType {
	return &file_service_usage_protos_manager_proto_enumTypes[2]
}

func (x RankingRequest_Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankingRequest_Target.Descriptor instead.
func (RankingRequest_Target) EnumDescriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{13, 0}
}

type RankingRequest_OwnerType int32

const (
	RankingRequest_ANY  RankingRequest_OwnerType = 0
	RankingRequest_USER RankingRequest_OwnerType = 1
	RankingRequest_ORG  RankingRequest_OwnerType = 2
)

// Enum value maps for RankingRequest_OwnerType.
var (
	RankingRequest_OwnerType_name = map[int32]string{
		0: "ANY",
		1: "USER",
		2: "ORG",
	}
	RankingRequest_OwnerType_value = map[string]int32{
		"ANY":  0,
		"USER": 1,
		"ORG":  2,
	}
)

func (x RankingRequest_OwnerType) Enum() *RankingRequest_OwnerType {
	p := new(RankingRequest_OwnerType)
	*p = x
	return p
}

func (x RankingRequest_OwnerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankingRequest_OwnerType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_usage_protos_manager_proto_enumTypes[3].Descriptor()
}

func (RankingRequest_OwnerType) Type() protoreflect.EnumType {
	return &file_service_usage_protos_manager_proto_enumTypes[3]
}

func (x RankingRequest_OwnerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankingRequest_OwnerType.Descriptor instead.
func (RankingRequest_OwnerType) EnumDescriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{13, 1}
}

type CheckOverLimitExtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectOwner  string                 `protobuf:"bytes,1,opt,name=project_owner,json=projectOwner,proto3" json:"project_owner,omitempty"`
	ProjectSlug   string                 `protobuf:"bytes,2,opt,name=project_slug,json=projectSlug,proto3" json:"project_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOverLimitExtRequest) Reset() {
	*x = CheckOverLimitExtRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOverLimitExtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOverLimitExtRequest) ProtoMessage() {}

func (x *CheckOverLimitExtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOverLimitExtRequest.ProtoReflect.Descriptor instead.
func (*CheckOverLimitExtRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{0}
}

func (x *CheckOverLimitExtRequest) GetProjectOwner() string {
	if x != nil {
		return x.ProjectOwner
	}
	return ""
}

func (x *CheckOverLimitExtRequest) GetProjectSlug() string {
	if x != nil {
		return x.ProjectSlug
	}
	return ""
}

type CheckOverLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Now           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOverLimitRequest) Reset() {
	*x = CheckOverLimitRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOverLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOverLimitRequest) ProtoMessage() {}

func (x *CheckOverLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOverLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckOverLimitRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CheckOverLimitRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CheckOverLimitRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CheckOverLimitRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CheckOverLimitRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CheckOverLimitRequest) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

type CheckOverLimitResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Over          []string                       `protobuf:"bytes,1,rep,name=over,proto3" json:"over,omitempty"`
	OverDetail    []string                       `protobuf:"bytes,2,rep,name=over_detail,json=overDetail,proto3" json:"over_detail,omitempty"`
	Status        *CheckOverLimitResponse_Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOverLimitResponse) Reset() {
	*x = CheckOverLimitResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOverLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOverLimitResponse) ProtoMessage() {}

func (x *CheckOverLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOverLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckOverLimitResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{2}
}

func (x *CheckOverLimitResponse) GetOver() []string {
	if x != nil {
		return x.Over
	}
	return nil
}

func (x *CheckOverLimitResponse) GetOverDetail() []string {
	if x != nil {
		return x.OverDetail
	}
	return nil
}

func (x *CheckOverLimitResponse) GetStatus() *CheckOverLimitResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Dialogue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestTime   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	Tags          *Tags                  `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	Succeed       bool                   `protobuf:"varint,5,opt,name=succeed,proto3" json:"succeed,omitempty"`
	LatencyMs     uint32                 `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Units         uint64                 `protobuf:"varint,7,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dialogue) Reset() {
	*x = Dialogue{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dialogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dialogue) ProtoMessage() {}

func (x *Dialogue) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dialogue.ProtoReflect.Descriptor instead.
func (*Dialogue) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{3}
}

func (x *Dialogue) GetRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTime
	}
	return nil
}

func (x *Dialogue) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Dialogue) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *Dialogue) GetTags() *Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Dialogue) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *Dialogue) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Dialogue) GetUnits() uint64 {
	if x != nil {
		return x.Units
	}
	return 0
}

type AsyncSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dialogues     []*Dialogue            `protobuf:"bytes,1,rep,name=dialogues,proto3" json:"dialogues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncSaveRequest) Reset() {
	*x = AsyncSaveRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncSaveRequest) ProtoMessage() {}

func (x *AsyncSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncSaveRequest.ProtoReflect.Descriptor instead.
func (*AsyncSaveRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{4}
}

func (x *AsyncSaveRequest) GetDialogues() []*Dialogue {
	if x != nil {
		return x.Dialogues
	}
	return nil
}

type AsyncSaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncSaveResponse) Reset() {
	*x = AsyncSaveResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncSaveResponse) ProtoMessage() {}

func (x *AsyncSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncSaveResponse.ProtoReflect.Descriptor instead.
func (*AsyncSaveResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{5}
}

type Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	CustomTags    map[string]string      `protobuf:"bytes,4,rep,name=custom_tags,json=customTags,proto3" json:"custom_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tags) Reset() {
	*x = Tags{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{6}
}

func (x *Tags) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Tags) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tags) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Tags) GetCustomTags() map[string]string {
	if x != nil {
		return x.CustomTags
	}
	return nil
}

type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NatualMonth   bool                   `protobuf:"varint,1,opt,name=natual_month,json=natualMonth,proto3" json:"natual_month,omitempty"`
	Seconds       uint64                 `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{7}
}

func (x *Period) GetNatualMonth() bool {
	if x != nil {
		return x.NatualMonth
	}
	return false
}

func (x *Period) GetSeconds() uint64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type QueryTags struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sku             string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	SplitCustomTags bool                   `protobuf:"varint,4,opt,name=split_custom_tags,json=splitCustomTags,proto3" json:"split_custom_tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryTags) Reset() {
	*x = QueryTags{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTags) ProtoMessage() {}

func (x *QueryTags) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTags.ProtoReflect.Descriptor instead.
func (*QueryTags) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTags) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *QueryTags) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryTags) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *QueryTags) GetSplitCustomTags() bool {
	if x != nil {
		return x.SplitCustomTags
	}
	return false
}

type SkuCostConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Cost          uint64                 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	EffectiveFrom *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuCostConfig) Reset() {
	*x = SkuCostConfig{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuCostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuCostConfig) ProtoMessage() {}

func (x *SkuCostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuCostConfig.ProtoReflect.Descriptor instead.
func (*SkuCostConfig) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{9}
}

func (x *SkuCostConfig) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *SkuCostConfig) GetCost() uint64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SkuCostConfig) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

type Sku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Cost          uint64                 `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	Visible       bool                   `protobuf:"varint,7,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sku) Reset() {
	*x = Sku{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sku) ProtoMessage() {}

func (x *Sku) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sku.ProtoReflect.Descriptor instead.
func (*Sku) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{10}
}

func (x *Sku) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sku) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sku) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Sku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sku) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Sku) GetCost() uint64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Sku) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type StatisticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,2,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	Tags          *QueryTags             `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Period        *Period                `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticRequest) Reset() {
	*x = StatisticRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticRequest) ProtoMessage() {}

func (x *StatisticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticRequest.ProtoReflect.Descriptor instead.
func (*StatisticRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{11}
}

func (x *StatisticRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StatisticRequest) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *StatisticRequest) GetTags() *QueryTags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StatisticRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *StatisticRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StatisticRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type StatisticResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Stats         []*StatisticResponse_Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticResponse) Reset() {
	*x = StatisticResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticResponse) ProtoMessage() {}

func (x *StatisticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticResponse.ProtoReflect.Descriptor instead.
func (*StatisticResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{12}
}

func (x *StatisticResponse) GetStats() []*StatisticResponse_Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type RankingRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Target        RankingRequest_Target    `protobuf:"varint,1,opt,name=target,proto3,enum=usage_service.RankingRequest_Target" json:"target,omitempty"`
	Sku           string                   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	UserId        string                   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OwnerId       string                   `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     RankingRequest_OwnerType `protobuf:"varint,8,opt,name=owner_type,json=ownerType,proto3,enum=usage_service.RankingRequest_OwnerType" json:"owner_type,omitempty"`
	Period        *Period                  `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	Time          *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Offset        uint32                   `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                   `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingRequest) Reset() {
	*x = RankingRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingRequest) ProtoMessage() {}

func (x *RankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingRequest.ProtoReflect.Descriptor instead.
func (*RankingRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{13}
}

func (x *RankingRequest) GetTarget() RankingRequest_Target {
	if x != nil {
		return x.Target
	}
	return RankingRequest_OWNER
}

func (x *RankingRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *RankingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RankingRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RankingRequest) GetOwnerType() RankingRequest_OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return RankingRequest_ANY
}

func (x *RankingRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *RankingRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *RankingRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RankingRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSkuCostConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IgnoreHistory bool                   `protobuf:"varint,1,opt,name=ignore_history,json=ignoreHistory,proto3" json:"ignore_history,omitempty"`
	IgnoreFuture  bool                   `protobuf:"varint,2,opt,name=ignore_future,json=ignoreFuture,proto3" json:"ignore_future,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkuCostConfigRequest) Reset() {
	*x = ListSkuCostConfigRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkuCostConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkuCostConfigRequest) ProtoMessage() {}

func (x *ListSkuCostConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkuCostConfigRequest.ProtoReflect.Descriptor instead.
func (*ListSkuCostConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{14}
}

func (x *ListSkuCostConfigRequest) GetIgnoreHistory() bool {
	if x != nil {
		return x.IgnoreHistory
	}
	return false
}

func (x *ListSkuCostConfigRequest) GetIgnoreFuture() bool {
	if x != nil {
		return x.IgnoreFuture
	}
	return false
}

type ListSkuCostConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*SkuCostConfig       `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkuCostConfigResponse) Reset() {
	*x = ListSkuCostConfigResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkuCostConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkuCostConfigResponse) ProtoMessage() {}

func (x *ListSkuCostConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkuCostConfigResponse.ProtoReflect.Descriptor instead.
func (*ListSkuCostConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{15}
}

func (x *ListSkuCostConfigResponse) GetConfigs() []*SkuCostConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type SetSkuCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*SkuCostConfig       `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSkuCostRequest) Reset() {
	*x = SetSkuCostRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSkuCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSkuCostRequest) ProtoMessage() {}

func (x *SetSkuCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSkuCostRequest.ProtoReflect.Descriptor instead.
func (*SetSkuCostRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{16}
}

func (x *SetSkuCostRequest) GetConfigs() []*SkuCostConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type DelSkuCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	EffectiveFrom *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSkuCostRequest) Reset() {
	*x = DelSkuCostRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSkuCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSkuCostRequest) ProtoMessage() {}

func (x *DelSkuCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSkuCostRequest.ProtoReflect.Descriptor instead.
func (*DelSkuCostRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{17}
}

func (x *DelSkuCostRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DelSkuCostRequest) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

type SetSkuCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSkuCostResponse) Reset() {
	*x = SetSkuCostResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSkuCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSkuCostResponse) ProtoMessage() {}

func (x *SetSkuCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSkuCostResponse.ProtoReflect.Descriptor instead.
func (*SetSkuCostResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{18}
}

type DelSkuCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelSkuCostResponse) Reset() {
	*x = DelSkuCostResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelSkuCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelSkuCostResponse) ProtoMessage() {}

func (x *DelSkuCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelSkuCostResponse.ProtoReflect.Descriptor instead.
func (*DelSkuCostResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{19}
}

type ListSKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	WithInvisible bool                   `protobuf:"varint,2,opt,name=with_invisible,json=withInvisible,proto3" json:"with_invisible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSKURequest) Reset() {
	*x = ListSKURequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSKURequest) ProtoMessage() {}

func (x *ListSKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSKURequest.ProtoReflect.Descriptor instead.
func (*ListSKURequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{20}
}

func (x *ListSKURequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ListSKURequest) GetWithInvisible() bool {
	if x != nil {
		return x.WithInvisible
	}
	return false
}

type ListSKUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuList       []*Sku                 `protobuf:"bytes,1,rep,name=sku_list,json=skuList,proto3" json:"sku_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSKUResponse) Reset() {
	*x = ListSKUResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSKUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSKUResponse) ProtoMessage() {}

func (x *ListSKUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSKUResponse.ProtoReflect.Descriptor instead.
func (*ListSKUResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{21}
}

func (x *ListSKUResponse) GetSkuList() []*Sku {
	if x != nil {
		return x.SkuList
	}
	return nil
}

type UpdateSKUMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Visible       bool                   `protobuf:"varint,6,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSKUMetaRequest) Reset() {
	*x = UpdateSKUMetaRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSKUMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSKUMetaRequest) ProtoMessage() {}

func (x *UpdateSKUMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSKUMetaRequest.ProtoReflect.Descriptor instead.
func (*UpdateSKUMetaRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateSKUMetaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSKUMetaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSKUMetaRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateSKUMetaRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type CheckQueryBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Signer        string                 `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQueryBalanceRequest) Reset() {
	*x = CheckQueryBalanceRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQueryBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQueryBalanceRequest) ProtoMessage() {}

func (x *CheckQueryBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQueryBalanceRequest.ProtoReflect.Descriptor instead.
func (*CheckQueryBalanceRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{23}
}

func (x *CheckQueryBalanceRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CheckQueryBalanceRequest) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

type CheckQueryBalanceResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        bool                       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason        CheckQueryBalanceRejection `protobuf:"varint,2,opt,name=reason,proto3,enum=usage_service.CheckQueryBalanceRejection" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQueryBalanceResponse) Reset() {
	*x = CheckQueryBalanceResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQueryBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQueryBalanceResponse) ProtoMessage() {}

func (x *CheckQueryBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQueryBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckQueryBalanceResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{24}
}

func (x *CheckQueryBalanceResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CheckQueryBalanceResponse) GetReason() CheckQueryBalanceRejection {
	if x != nil {
		return x.Reason
	}
	return CheckQueryBalanceRejection_UNKNOWN
}

type ReportQueryUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Signer        string                 `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportQueryUsageRequest) Reset() {
	*x = ReportQueryUsageRequest{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportQueryUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportQueryUsageRequest) ProtoMessage() {}

func (x *ReportQueryUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportQueryUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportQueryUsageRequest) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{25}
}

func (x *ReportQueryUsageRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReportQueryUsageRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReportQueryUsageRequest) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

type ReportQueryUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportQueryUsageResponse) Reset() {
	*x = ReportQueryUsageResponse{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportQueryUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportQueryUsageResponse) ProtoMessage() {}

func (x *ReportQueryUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportQueryUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportQueryUsageResponse) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{26}
}

type CheckOverLimitResponse_Limiter struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Category      CheckOverLimitResponse_Limiter_Category `protobuf:"varint,1,opt,name=category,proto3,enum=usage_service.CheckOverLimitResponse_Limiter_Category" json:"category,omitempty"`
	EffectiveTime *timestamppb.Timestamp                  `protobuf:"bytes,2,opt,name=effective_time,json=effectiveTime,proto3" json:"effective_time,omitempty"`
	ExpireTime    *timestamppb.Timestamp                  `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	OwnerId       string                                  `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                                  `protobuf:"bytes,5,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	ProjectId     string                                  `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Sku           string                                  `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	Period        *Period                                 `protobuf:"bytes,8,opt,name=period,proto3" json:"period,omitempty"`
	Cost          uint64                                  `protobuf:"varint,9,opt,name=cost,proto3" json:"cost,omitempty"`
	Succeed       uint64                                  `protobuf:"varint,10,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOverLimitResponse_Limiter) Reset() {
	*x = CheckOverLimitResponse_Limiter{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOverLimitResponse_Limiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOverLimitResponse_Limiter) ProtoMessage() {}

func (x *CheckOverLimitResponse_Limiter) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOverLimitResponse_Limiter.ProtoReflect.Descriptor instead.
func (*CheckOverLimitResponse_Limiter) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CheckOverLimitResponse_Limiter) GetCategory() CheckOverLimitResponse_Limiter_Category {
	if x != nil {
		return x.Category
	}
	return CheckOverLimitResponse_Limiter_OWNER_LIMITER
}

func (x *CheckOverLimitResponse_Limiter) GetEffectiveTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveTime
	}
	return nil
}

func (x *CheckOverLimitResponse_Limiter) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

func (x *CheckOverLimitResponse_Limiter) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CheckOverLimitResponse_Limiter) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CheckOverLimitResponse_Limiter) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CheckOverLimitResponse_Limiter) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CheckOverLimitResponse_Limiter) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *CheckOverLimitResponse_Limiter) GetCost() uint64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CheckOverLimitResponse_Limiter) GetSucceed() uint64 {
	if x != nil {
		return x.Succeed
	}
	return 0
}

type CheckOverLimitResponse_OverLimiterStatus struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Limiter        *CheckOverLimitResponse_Limiter `protobuf:"bytes,1,opt,name=limiter,proto3" json:"limiter,omitempty"`
	CurrentCost    uint64                          `protobuf:"varint,2,opt,name=current_cost,json=currentCost,proto3" json:"current_cost,omitempty"`
	CurrentSucceed uint64                          `protobuf:"varint,3,opt,name=current_succeed,json=currentSucceed,proto3" json:"current_succeed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckOverLimitResponse_OverLimiterStatus) Reset() {
	*x = CheckOverLimitResponse_OverLimiterStatus{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOverLimitResponse_OverLimiterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOverLimitResponse_OverLimiterStatus) ProtoMessage() {}

func (x *CheckOverLimitResponse_OverLimiterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOverLimitResponse_OverLimiterStatus.ProtoReflect.Descriptor instead.
func (*CheckOverLimitResponse_OverLimiterStatus) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CheckOverLimitResponse_OverLimiterStatus) GetLimiter() *CheckOverLimitResponse_Limiter {
	if x != nil {
		return x.Limiter
	}
	return nil
}

func (x *CheckOverLimitResponse_OverLimiterStatus) GetCurrentCost() uint64 {
	if x != nil {
		return x.CurrentCost
	}
	return 0
}

func (x *CheckOverLimitResponse_OverLimiterStatus) GetCurrentSucceed() uint64 {
	if x != nil {
		return x.CurrentSucceed
	}
	return 0
}

type CheckOverLimitResponse_Status struct {
	state            protoimpl.MessageState                      `protogen:"open.v1"`
	AccountSuspended bool                                        `protobuf:"varint,1,opt,name=account_suspended,json=accountSuspended,proto3" json:"account_suspended,omitempty"`
	Limiters         []*CheckOverLimitResponse_OverLimiterStatus `protobuf:"bytes,2,rep,name=limiters,proto3" json:"limiters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckOverLimitResponse_Status) Reset() {
	*x = CheckOverLimitResponse_Status{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOverLimitResponse_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOverLimitResponse_Status) ProtoMessage() {}

func (x *CheckOverLimitResponse_Status) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOverLimitResponse_Status.ProtoReflect.Descriptor instead.
func (*CheckOverLimitResponse_Status) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{2, 2}
}

func (x *CheckOverLimitResponse_Status) GetAccountSuspended() bool {
	if x != nil {
		return x.AccountSuspended
	}
	return false
}

func (x *CheckOverLimitResponse_Status) GetLimiters() []*CheckOverLimitResponse_OverLimiterStatus {
	if x != nil {
		return x.Limiters
	}
	return nil
}

type StatisticResponse_Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeWindow    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	OwnerId       string                 `protobuf:"bytes,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,10,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	Tags          *Tags                  `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
	Cost          uint64                 `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Units         uint64                 `protobuf:"varint,8,opt,name=units,proto3" json:"units,omitempty"`
	Succeed       uint64                 `protobuf:"varint,4,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Total         uint64                 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	LatencyMsMax  uint32                 `protobuf:"varint,6,opt,name=latency_ms_max,json=latencyMsMax,proto3" json:"latency_ms_max,omitempty"`
	LatencyMsAvg  uint32                 `protobuf:"varint,7,opt,name=latency_ms_avg,json=latencyMsAvg,proto3" json:"latency_ms_avg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticResponse_Stat) Reset() {
	*x = StatisticResponse_Stat{}
	mi := &file_service_usage_protos_manager_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticResponse_Stat) ProtoMessage() {}

func (x *StatisticResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_service_usage_protos_manager_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticResponse_Stat.ProtoReflect.Descriptor instead.
func (*StatisticResponse_Stat) Descriptor() ([]byte, []int) {
	return file_service_usage_protos_manager_proto_rawDescGZIP(), []int{12, 0}
}

func (x *StatisticResponse_Stat) GetTimeWindow() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeWindow
	}
	return nil
}

func (x *StatisticResponse_Stat) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StatisticResponse_Stat) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *StatisticResponse_Stat) GetTags() *Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StatisticResponse_Stat) GetCost() uint64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *StatisticResponse_Stat) GetUnits() uint64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *StatisticResponse_Stat) GetSucceed() uint64 {
	if x != nil {
		return x.Succeed
	}
	return 0
}

func (x *StatisticResponse_Stat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatisticResponse_Stat) GetLatencyMsMax() uint32 {
	if x != nil {
		return x.LatencyMsMax
	}
	return 0
}

func (x *StatisticResponse_Stat) GetLatencyMsAvg() uint32 {
	if x != nil {
		return x.LatencyMsAvg
	}
	return 0
}

var File_service_usage_protos_manager_proto protoreflect.FileDescriptor

const file_service_usage_protos_manager_proto_rawDesc = "" +
	"\n" +
	"\"service/usage/protos/manager.proto\x12\rusage_service\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x18CheckOverLimitExtRequest\x12#\n" +
	"\rproject_owner\x18\x01 \x01(\tR\fprojectOwner\x12!\n" +
	"\fproject_slug\x18\x02 \x01(\tR\vprojectSlug\"\xb0\x01\n" +
	"\x15CheckOverLimitRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12,\n" +
	"\x03now\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\"\xac\a\n" +
	"\x16CheckOverLimitResponse\x12\x12\n" +
	"\x04over\x18\x01 \x03(\tR\x04over\x12\x1f\n" +
	"\vover_detail\x18\x02 \x03(\tR\n" +
	"overDetail\x12D\n" +
	"\x06status\x18\x03 \x01(\v2,.usage_service.CheckOverLimitResponse.StatusR\x06status\x1a\xde\x03\n" +
	"\aLimiter\x12R\n" +
	"\bcategory\x18\x01 \x01(\x0e26.usage_service.CheckOverLimitResponse.Limiter.CategoryR\bcategory\x12A\n" +
	"\x0eeffective_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveTime\x12;\n" +
	"\vexpire_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x05 \x01(\tR\townerType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12-\n" +
	"\x06period\x18\b \x01(\v2\x15.usage_service.PeriodR\x06period\x12\x12\n" +
	"\x04cost\x18\t \x01(\x04R\x04cost\x12\x18\n" +
	"\asucceed\x18\n" +
	" \x01(\x04R\asucceed\"7\n" +
	"\bCategory\x12\x11\n" +
	"\rOWNER_LIMITER\x10\x00\x12\x18\n" +
	"\x14DEFAULT_TIER_LIMITER\x10\x01\x1a\xa8\x01\n" +
	"\x11OverLimiterStatus\x12G\n" +
	"\alimiter\x18\x01 \x01(\v2-.usage_service.CheckOverLimitResponse.LimiterR\alimiter\x12!\n" +
	"\fcurrent_cost\x18\x02 \x01(\x04R\vcurrentCost\x12'\n" +
	"\x0fcurrent_succeed\x18\x03 \x01(\x04R\x0ecurrentSucceed\x1a\x8a\x01\n" +
	"\x06Status\x12+\n" +
	"\x11account_suspended\x18\x01 \x01(\bR\x10accountSuspended\x12S\n" +
	"\blimiters\x18\x02 \x03(\v27.usage_service.CheckOverLimitResponse.OverLimiterStatusR\blimiters\"\xfb\x01\n" +
	"\bDialogue\x12=\n" +
	"\frequest_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestTime\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tR\townerType\x12'\n" +
	"\x04tags\x18\x04 \x01(\v2\x13.usage_service.TagsR\x04tags\x12\x18\n" +
	"\asucceed\x18\x05 \x01(\bR\asucceed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\rR\tlatencyMs\x12\x14\n" +
	"\x05units\x18\a \x01(\x04R\x05units\"I\n" +
	"\x10AsyncSaveRequest\x125\n" +
	"\tdialogues\x18\x01 \x03(\v2\x17.usage_service.DialogueR\tdialogues\"\x13\n" +
	"\x11AsyncSaveResponse\"\xd5\x01\n" +
	"\x04Tags\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12D\n" +
	"\vcustom_tags\x18\x04 \x03(\v2#.usage_service.Tags.CustomTagsEntryR\n" +
	"customTags\x1a=\n" +
	"\x0fCustomTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x06Period\x12!\n" +
	"\fnatual_month\x18\x01 \x01(\bR\vnatualMonth\x12\x18\n" +
	"\aseconds\x18\x02 \x01(\x04R\aseconds\"\x81\x01\n" +
	"\tQueryTags\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12*\n" +
	"\x11split_custom_tags\x18\x04 \x01(\bR\x0fsplitCustomTags\"x\n" +
	"\rSkuCostConfig\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x04R\x04cost\x12A\n" +
	"\x0eeffective_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\"\xe1\x01\n" +
	"\x03Sku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x04R\x04cost\x12\x18\n" +
	"\avisible\x18\a \x01(\bR\avisible\"\x9b\x02\n" +
	"\x10StatisticRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\tR\townerType\x12,\n" +
	"\x04tags\x18\x03 \x01(\v2\x18.usage_service.QueryTagsR\x04tags\x12-\n" +
	"\x06period\x18\x04 \x01(\v2\x15.usage_service.PeriodR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x9f\x03\n" +
	"\x11StatisticResponse\x12;\n" +
	"\x05stats\x18\x01 \x03(\v2%.usage_service.StatisticResponse.StatR\x05stats\x1a\xcc\x02\n" +
	"\x04Stat\x12;\n" +
	"\vtime_window\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeWindow\x12\x19\n" +
	"\bowner_id\x18\t \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\n" +
	" \x01(\tR\townerType\x12'\n" +
	"\x04tags\x18\x02 \x01(\v2\x13.usage_service.TagsR\x04tags\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x04R\x04cost\x12\x14\n" +
	"\x05units\x18\b \x01(\x04R\x05units\x12\x18\n" +
	"\asucceed\x18\x04 \x01(\x04R\asucceed\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x04R\x05total\x12$\n" +
	"\x0elatency_ms_max\x18\x06 \x01(\rR\flatencyMsMax\x12$\n" +
	"\x0elatency_ms_avg\x18\a \x01(\rR\flatencyMsAvg\"\xb4\x03\n" +
	"\x0eRankingRequest\x12<\n" +
	"\x06target\x18\x01 \x01(\x0e2$.usage_service.RankingRequest.TargetR\x06target\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12F\n" +
	"\n" +
	"owner_type\x18\b \x01(\x0e2'.usage_service.RankingRequest.OwnerTypeR\townerType\x12-\n" +
	"\x06period\x18\x04 \x01(\v2\x15.usage_service.PeriodR\x06period\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x16\n" +
	"\x06offset\x18\t \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\" \n" +
	"\x06Target\x12\t\n" +
	"\x05OWNER\x10\x00\x12\v\n" +
	"\aPROJECT\x10\x01\"'\n" +
	"\tOwnerType\x12\a\n" +
	"\x03ANY\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\a\n" +
	"\x03ORG\x10\x02\"f\n" +
	"\x18ListSkuCostConfigRequest\x12%\n" +
	"\x0eignore_history\x18\x01 \x01(\bR\rignoreHistory\x12#\n" +
	"\rignore_future\x18\x02 \x01(\bR\fignoreFuture\"S\n" +
	"\x19ListSkuCostConfigResponse\x126\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1c.usage_service.SkuCostConfigR\aconfigs\"K\n" +
	"\x11SetSkuCostRequest\x126\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1c.usage_service.SkuCostConfigR\aconfigs\"h\n" +
	"\x11DelSkuCostRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12A\n" +
	"\x0eeffective_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\"\x14\n" +
	"\x12SetSkuCostResponse\"\x14\n" +
	"\x12DelSkuCostResponse\"g\n" +
	"\x0eListSKURequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12%\n" +
	"\x0ewith_invisible\x18\x02 \x01(\bR\rwithInvisible\"@\n" +
	"\x0fListSKUResponse\x12-\n" +
	"\bsku_list\x18\x01 \x03(\v2\x12.usage_service.SkuR\askuList\"h\n" +
	"\x14UpdateSKUMetaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\"L\n" +
	"\x18CheckQueryBalanceRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06signer\x18\x02 \x01(\tR\x06signer\"v\n" +
	"\x19CheckQueryBalanceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12A\n" +
	"\x06reason\x18\x02 \x01(\x0e2).usage_service.CheckQueryBalanceRejectionR\x06reason\"c\n" +
	"\x17ReportQueryUsageRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06signer\x18\x03 \x01(\tR\x06signer\"\x1a\n" +
	"\x18ReportQueryUsageResponse*\\\n" +
	"\x1aCheckQueryBalanceRejection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x18\n" +
	"\x14INSUFFICIENT_BALANCE\x10\x01\x12\x17\n" +
	"\x13UNAUTHORIZED_SIGNER\x10\x022\x99\f\n" +
	"\fUsageService\x12N\n" +
	"\tAsyncSave\x12\x1f.usage_service.AsyncSaveRequest\x1a .usage_service.AsyncSaveResponse\x12]\n" +
	"\x0eCheckOverLimit\x12$.usage_service.CheckOverLimitRequest\x1a%.usage_service.CheckOverLimitResponse\x12N\n" +
	"\tStatistic\x12\x1f.usage_service.StatisticRequest\x1a .usage_service.StatisticResponse\x12\x95\x01\n" +
	"\x11CheckOverLimitExt\x12'.usage_service.CheckOverLimitExtRequest\x1a%.usage_service.CheckOverLimitResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/gateway-manager/check-over-limit\x12|\n" +
	"\fStatisticExt\x12\x1f.usage_service.StatisticRequest\x1a .usage_service.StatisticResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/gateway-manager/statistic\x12\x84\x01\n" +
	"\x0eStatisticAdmin\x12\x1f.usage_service.StatisticRequest\x1a .usage_service.StatisticResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/gateway-manager/admin/statistic\x12J\n" +
	"\aRanking\x12\x1d.usage_service.RankingRequest\x1a .usage_service.StatisticResponse\x12~\n" +
	"\fRankingAdmin\x12\x1d.usage_service.RankingRequest\x1a .usage_service.StatisticResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/gateway-manager/admin/ranking\x12\x9b\x01\n" +
	"\x16ListSkuCostConfigAdmin\x12'.usage_service.ListSkuCostConfigRequest\x1a(.usage_service.ListSkuCostConfigResponse\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/gateway-manager/admin/sku-cost\x12\x89\x01\n" +
	"\x0fSetSkuCostAdmin\x12 .usage_service.SetSkuCostRequest\x1a!.usage_service.SetSkuCostResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/gateway-manager/admin/sku-cost\x12\x86\x01\n" +
	"\x0fDelSkuCostAdmin\x12 .usage_service.DelSkuCostRequest\x1a!.usage_service.DelSkuCostResponse\".\x82\xd3\xe4\x93\x02(*&/api/v1/gateway-manager/admin/sku-cost\x12m\n" +
	"\aListSKU\x12\x1d.usage_service.ListSKURequest\x1a\x1e.usage_service.ListSKUResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/gateway-manager/sku\x12\x7f\n" +
	"\x12UpdateSKUMetaAdmin\x12#.usage_service.UpdateSKUMetaRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/gateway-manager/admin/sku2\xe0\x01\n" +
	"\x11QueryUsageService\x12f\n" +
	"\x11CheckQueryBalance\x12'.usage_service.CheckQueryBalanceRequest\x1a(.usage_service.CheckQueryBalanceResponse\x12c\n" +
	"\x10ReportQueryUsage\x12&.usage_service.ReportQueryUsageRequest\x1a'.usage_service.ReportQueryUsageResponseB,Z*sentioxyz/sentio-core/service/usage/protosb\x06proto3"

var (
	file_service_usage_protos_manager_proto_rawDescOnce sync.Once
	file_service_usage_protos_manager_proto_rawDescData []byte
)

func file_service_usage_protos_manager_proto_rawDescGZIP() []byte {
	file_service_usage_protos_manager_proto_rawDescOnce.Do(func() {
		file_service_usage_protos_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_usage_protos_manager_proto_rawDesc), len(file_service_usage_protos_manager_proto_rawDesc)))
	})
	return file_service_usage_protos_manager_proto_rawDescData
}

var file_service_usage_protos_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_service_usage_protos_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_service_usage_protos_manager_proto_goTypes = []any{
	(CheckQueryBalanceRejection)(0),                  // 0: usage_service.CheckQueryBalanceRejection
	(CheckOverLimitResponse_Limiter_Category)(0),     // 1: usage_service.CheckOverLimitResponse.Limiter.Category
	(RankingRequest_Target)(0),                       // 2: usage_service.RankingRequest.Target
	(RankingRequest_OwnerType)(0),                    // 3: usage_service.RankingRequest.OwnerType
	(*CheckOverLimitExtRequest)(nil),                 // 4: usage_service.CheckOverLimitExtRequest
	(*CheckOverLimitRequest)(nil),                    // 5: usage_service.CheckOverLimitRequest
	(*CheckOverLimitResponse)(nil),                   // 6: usage_service.CheckOverLimitResponse
	(*Dialogue)(nil),                                 // 7: usage_service.Dialogue
	(*AsyncSaveRequest)(nil),                         // 8: usage_service.AsyncSaveRequest
	(*AsyncSaveResponse)(nil),                        // 9: usage_service.AsyncSaveResponse
	(*Tags)(nil),                                     // 10: usage_service.Tags
	(*Period)(nil),                                   // 11: usage_service.Period
	(*QueryTags)(nil),                                // 12: usage_service.QueryTags
	(*SkuCostConfig)(nil),                            // 13: usage_service.SkuCostConfig
	(*Sku)(nil),                                      // 14: usage_service.Sku
	(*StatisticRequest)(nil),                         // 15: usage_service.StatisticRequest
	(*StatisticResponse)(nil),                        // 16: usage_service.StatisticResponse
	(*RankingRequest)(nil),                           // 17: usage_service.RankingRequest
	(*ListSkuCostConfigRequest)(nil),                 // 18: usage_service.ListSkuCostConfigRequest
	(*ListSkuCostConfigResponse)(nil),                // 19: usage_service.ListSkuCostConfigResponse
	(*SetSkuCostRequest)(nil),                        // 20: usage_service.SetSkuCostRequest
	(*DelSkuCostRequest)(nil),                        // 21: usage_service.DelSkuCostRequest
	(*SetSkuCostResponse)(nil),                       // 22: usage_service.SetSkuCostResponse
	(*DelSkuCostResponse)(nil),                       // 23: usage_service.DelSkuCostResponse
	(*ListSKURequest)(nil),                           // 24: usage_service.ListSKURequest
	(*ListSKUResponse)(nil),                          // 25: usage_service.ListSKUResponse
	(*UpdateSKUMetaRequest)(nil),                     // 26: usage_service.UpdateSKUMetaRequest
	(*CheckQueryBalanceRequest)(nil),                 // 27: usage_service.CheckQueryBalanceRequest
	(*CheckQueryBalanceResponse)(nil),                // 28: usage_service.CheckQueryBalanceResponse
	(*ReportQueryUsageRequest)(nil),                  // 29: usage_service.ReportQueryUsageRequest
	(*ReportQueryUsageResponse)(nil),                 // 30: usage_service.ReportQueryUsageResponse
	(*CheckOverLimitResponse_Limiter)(nil),           // 31: usage_service.CheckOverLimitResponse.Limiter
	(*CheckOverLimitResponse_OverLimiterStatus)(nil), // 32: usage_service.CheckOverLimitResponse.OverLimiterStatus
	(*CheckOverLimitResponse_Status)(nil),            // 33: usage_service.CheckOverLimitResponse.Status
	nil,                                              // 34: usage_service.Tags.CustomTagsEntry
	(*StatisticResponse_Stat)(nil),                   // 35: usage_service.StatisticResponse.Stat
	(*timestamppb.Timestamp)(nil),                    // 36: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                            // 37: google.protobuf.Empty
}
var file_service_usage_protos_manager_proto_depIdxs = []int32{
	36, // 0: usage_service.CheckOverLimitRequest.now:type_name -> google.protobuf.Timestamp
	33, // 1: usage_service.CheckOverLimitResponse.status:type_name -> usage_service.CheckOverLimitResponse.Status
	36, // 2: usage_service.Dialogue.request_time:type_name -> google.protobuf.Timestamp
	10, // 3: usage_service.Dialogue.tags:type_name -> usage_service.Tags
	7,  // 4: usage_service.AsyncSaveRequest.dialogues:type_name -> usage_service.Dialogue
	34, // 5: usage_service.Tags.custom_tags:type_name -> usage_service.Tags.CustomTagsEntry
	36, // 6: usage_service.SkuCostConfig.effective_from:type_name -> google.protobuf.Timestamp
	36, // 7: usage_service.Sku.created_at:type_name -> google.protobuf.Timestamp
	36, // 8: usage_service.Sku.updated_at:type_name -> google.protobuf.Timestamp
	12, // 9: usage_service.StatisticRequest.tags:type_name -> usage_service.QueryTags
	11, // 10: usage_service.StatisticRequest.period:type_name -> usage_service.Period
	36, // 11: usage_service.StatisticRequest.start_time:type_name -> google.protobuf.Timestamp
	36, // 12: usage_service.StatisticRequest.end_time:type_name -> google.protobuf.Timestamp
	35, // 13: usage_service.StatisticResponse.stats:type_name -> usage_service.StatisticResponse.Stat
	2,  // 14: usage_service.RankingRequest.target:type_name -> usage_service.RankingRequest.Target
	3,  // 15: usage_service.RankingRequest.owner_type:type_name -> usage_service.RankingRequest.OwnerType
	11, // 16: usage_service.RankingRequest.period:type_name -> usage_service.Period
	36, // 17: usage_service.RankingRequest.time:type_name -> google.protobuf.Timestamp
	13, // 18: usage_service.ListSkuCostConfigResponse.configs:type_name -> usage_service.SkuCostConfig
	13, // 19: usage_service.SetSkuCostRequest.configs:type_name -> usage_service.SkuCostConfig
	36, // 20: usage_service.DelSkuCostRequest.effective_from:type_name -> google.protobuf.Timestamp
	36, // 21: usage_service.ListSKURequest.time:type_name -> google.protobuf.Timestamp
	14, // 22: usage_service.ListSKUResponse.sku_list:type_name -> usage_service.Sku
	0,  // 23: usage_service.CheckQueryBalanceResponse.reason:type_name -> usage_service.CheckQueryBalanceRejection
	1,  // 24: usage_service.CheckOverLimitResponse.Limiter.category:type_name -> usage_service.CheckOverLimitResponse.Limiter.Category
	36, // 25: usage_service.CheckOverLimitResponse.Limiter.effective_time:type_name -> google.protobuf.Timestamp
	36, // 26: usage_service.CheckOverLimitResponse.Limiter.expire_time:type_name -> google.protobuf.Timestamp
	11, // 27: usage_service.CheckOverLimitResponse.Limiter.period:type_name -> usage_service.Period
	31, // 28: usage_service.CheckOverLimitResponse.OverLimiterStatus.limiter:type_name -> usage_service.CheckOverLimitResponse.Limiter
	32, // 29: usage_service.CheckOverLimitResponse.Status.limiters:type_name -> usage_service.CheckOverLimitResponse.OverLimiterStatus
	36, // 30: usage_service.StatisticResponse.Stat.time_window:type_name -> google.protobuf.Timestamp
	10, // 31: usage_service.StatisticResponse.Stat.tags:type_name -> usage_service.Tags
	8,  // 32: usage_service.UsageService.AsyncSave:input_type -> usage_service.AsyncSaveRequest
	5,  // 33: usage_service.UsageService.CheckOverLimit:input_type -> usage_service.CheckOverLimitRequest
	15, // 34: usage_service.UsageService.Statistic:input_type -> usage_service.StatisticRequest
	4,  // 35: usage_service.UsageService.CheckOverLimitExt:input_type -> usage_service.CheckOverLimitExtRequest
	15, // 36: usage_service.UsageService.StatisticExt:input_type -> usage_service.StatisticRequest
	15, // 37: usage_service.UsageService.StatisticAdmin:input_type -> usage_service.StatisticRequest
	17, // 38: usage_service.UsageService.Ranking:input_type -> usage_service.RankingRequest
	17, // 39: usage_service.UsageService.RankingAdmin:input_type -> usage_service.RankingRequest
	18, // 40: usage_service.UsageService.ListSkuCostConfigAdmin:input_type -> usage_service.ListSkuCostConfigRequest
	20, // 41: usage_service.UsageService.SetSkuCostAdmin:input_type -> usage_service.SetSkuCostRequest
	21, // 42: usage_service.UsageService.DelSkuCostAdmin:input_type -> usage_service.DelSkuCostRequest
	24, // 43: usage_service.UsageService.ListSKU:input_type -> usage_service.ListSKURequest
	26, // 44: usage_service.UsageService.UpdateSKUMetaAdmin:input_type -> usage_service.UpdateSKUMetaRequest
	27, // 45: usage_service.QueryUsageService.CheckQueryBalance:input_type -> usage_service.CheckQueryBalanceRequest
	29, // 46: usage_service.QueryUsageService.ReportQueryUsage:input_type -> usage_service.ReportQueryUsageRequest
	9,  // 47: usage_service.UsageService.AsyncSave:output_type -> usage_service.AsyncSaveResponse
	6,  // 48: usage_service.UsageService.CheckOverLimit:output_type -> usage_service.CheckOverLimitResponse
	16, // 49: usage_service.UsageService.Statistic:output_type -> usage_service.StatisticResponse
	6,  // 50: usage_service.UsageService.CheckOverLimitExt:output_type -> usage_service.CheckOverLimitResponse
	16, // 51: usage_service.UsageService.StatisticExt:output_type -> usage_service.StatisticResponse
	16, // 52: usage_service.UsageService.StatisticAdmin:output_type -> usage_service.StatisticResponse
	16, // 53: usage_service.UsageService.Ranking:output_type -> usage_service.StatisticResponse
	16, // 54: usage_service.UsageService.RankingAdmin:output_type -> usage_service.StatisticResponse
	19, // 55: usage_service.UsageService.ListSkuCostConfigAdmin:output_type -> usage_service.ListSkuCostConfigResponse
	22, // 56: usage_service.UsageService.SetSkuCostAdmin:output_type -> usage_service.SetSkuCostResponse
	23, // 57: usage_service.UsageService.DelSkuCostAdmin:output_type -> usage_service.DelSkuCostResponse
	25, // 58: usage_service.UsageService.ListSKU:output_type -> usage_service.ListSKUResponse
	37, // 59: usage_service.UsageService.UpdateSKUMetaAdmin:output_type -> google.protobuf.Empty
	28, // 60: usage_service.QueryUsageService.CheckQueryBalance:output_type -> usage_service.CheckQueryBalanceResponse
	30, // 61: usage_service.QueryUsageService.ReportQueryUsage:output_type -> usage_service.ReportQueryUsageResponse
	47, // [47:62] is the sub-list for method output_type
	32, // [32:47] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_service_usage_protos_manager_proto_init() }
func file_service_usage_protos_manager_proto_init() {
	if File_service_usage_protos_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_usage_protos_manager_proto_rawDesc), len(file_service_usage_protos_manager_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_usage_protos_manager_proto_goTypes,
		DependencyIndexes: file_service_usage_protos_manager_proto_depIdxs,
		EnumInfos:         file_service_usage_protos_manager_proto_enumTypes,
		MessageInfos:      file_service_usage_protos_manager_proto_msgTypes,
	}.Build()
	File_service_usage_protos_manager_proto = out.File
	file_service_usage_protos_manager_proto_goTypes = nil
	file_service_usage_protos_manager_proto_depIdxs = nil
}
