/*
 * applyVisibilitySurface — rewrite a CodeGeneratorRequest so the generated code
 * contains exactly the API surface visible at a google.api visibility level
 * (google/api/visibility.proto; labels used as ascending audience levels
 * INTERNAL < PREVIEW < PUBLIC, unannotated = PUBLIC).
 *
 * This is what makes `es_proto(visibility_level = "PUBLIC")` safe to publish:
 * the output must not reveal the internal API surface that shares proto files
 * with the public one. Filtering methods alone is not enough — request/response
 * types of internal methods, internal fields, custom option bytes and internal
 * comments would all still leak through the generated TypeScript and the
 * embedded base64 descriptor. So, for every file being generated:
 *
 *   1. services below the level (api_visibility) are removed, methods below the
 *      level (method_visibility) are removed, and services left with no methods
 *      are removed entirely (even their name must not leak);
 *   2. fields below the level (field_visibility) are removed, pruning and
 *      reindexing oneofs as needed (incl. synthetic proto3-optional oneofs);
 *   3. enum values below the level (value_visibility) are removed; an enum left
 *      empty fails the build (annotate the enum itself instead). Removed values
 *      are safe at runtime: connect-gateway-es parses JSON with
 *      ignoreUnknownFields, and unknown numeric values pass through binary;
 *   4. message/enum types not reachable from the surviving methods are removed
 *      (reachability = transitive closure over surviving fields' type
 *      references, starting from surviving methods' request/response types; a
 *      below-level type that IS reachable is a contradiction and fails the
 *      build); extension declarations are always removed;
 *   5. each file's dependency list is recomputed from the surviving type
 *      references (options-only and now-unused imports are dropped);
 *   6. custom option bytes (descriptor unknown fields) are removed everywhere
 *      except (google.api.http) on surviving methods, which connect-gateway-es
 *      reads at runtime to route REST calls;
 *   7. `(-- internal --)` comment spans are stripped (grpc-gateway's
 *      remove_internal_comments convention) and SourceCodeInfo paths are
 *      remapped so surviving elements keep their (scrubbed) doc comments
 *      instead of silently re-attaching to the wrong elements;
 *   8. a final fail-closed walk asserts no below-level annotation survives.
 *
 * Reachability is computed within ONE CodeGeneratorRequest, so a published
 * surface must be generated by a single es_proto target listing every proto of
 * the surface (like the combined openapi target).
 *
 * Dependency files NOT in file_to_generate are never emitted, but they are
 * pruned in-memory all the same: their services are dropped outright and their
 * types pruned to the same reachable closure. A bystander dep that sits
 * between two generated files (gen A imports dep B imports gen C) would
 * otherwise keep fields referencing types pruned from C, and protoc-gen-es's
 * registry build fails on dangling references. Pruning bystanders is
 * unobservable in the output and keeps the registry consistent; a final
 * integrity walk turns any remaining dangling reference into a descriptive
 * build error instead of a bare assertion.
 *
 * Files in file_to_generate that lose all content still emit (keep_empty_files
 * is set by the rule); only the file name itself remains visible.
 */
import { BinaryReader, WireType } from '@bufbuild/protobuf/wire'

// Ascending google.api visibility audience levels; an unannotated element is
// PUBLIC. Index into this array = numeric level.
export const VISIBILITY_LEVELS = ['INTERNAL', 'PREVIEW', 'PUBLIC']
const PUBLIC_LEVEL = VISIBILITY_LEVELS.indexOf('PUBLIC')

// google/api/visibility.proto assigns extension number 72295727 to every
// *_visibility extension (Method/Service/Field/Message/Enum/EnumValue options),
// each a VisibilityRule message whose field 2 is `restriction`. The extension
// is never registered (visibility.proto is options-only, normally in
// ES_STRIP_IMPORTS), so the bytes sit in the options' unknown fields and are
// read from there.
const VISIBILITY_EXT_FIELD = 72295727

// (google.api.http) on MethodOptions — the one custom option the generated
// copy must keep: connect-gateway-es reads it at runtime to route REST calls.
const HTTP_EXT_FIELD = 72295728

// FieldDescriptorProto.type values whose type_name references another type.
const TYPE_REF_KINDS = new Set([
  10 /* GROUP */, 11 /* MESSAGE */, 14 /* ENUM */
])

// Returns the restriction string of a descriptor element's options, or
// undefined when unannotated.
export function restrictionOf(options) {
  let restriction
  for (const f of options?.$unknown ?? []) {
    if (
      f.no !== VISIBILITY_EXT_FIELD ||
      f.wireType !== WireType.LengthDelimited
    )
      continue
    // f.data is the length-prefixed VisibilityRule bytes. A repeated occurrence
    // of this singular extension merges per proto rules: last `restriction` wins.
    const rule = new BinaryReader(new BinaryReader(f.data).bytes())
    while (rule.pos < rule.len) {
      const [no, wt] = rule.tag()
      if (no === 2 && wt === WireType.LengthDelimited)
        restriction = rule.string()
      else rule.skip(wt, no)
    }
  }
  return restriction
}

// Maps a restriction label list to its level index; an empty list = PUBLIC.
// `restriction` is a comma-separated label list per google/api/visibility.proto
// ("INTERNAL,PREVIEW" = visible to both audiences); a multi-label element's
// level is its highest label. Unknown labels fail loudly — a typo must not
// silently add an element to (or hide it from) a public surface.
export function visibilityLevelOf(restriction, where) {
  let level = -1
  for (const part of restriction.split(',')) {
    const label = part.trim()
    if (!label) continue
    const idx = VISIBILITY_LEVELS.indexOf(label)
    if (idx === -1) {
      throw new Error(
        `protoc-gen-es: unknown google.api visibility restriction ` +
          `'${label}' on ${where}; known levels: ${VISIBILITY_LEVELS.join(' < ')}`
      )
    }
    if (idx > level) level = idx
  }
  return level === -1 ? PUBLIC_LEVEL : level
}

function levelOf(options, where) {
  const restriction = restrictionOf(options)
  return restriction === undefined
    ? PUBLIC_LEVEL
    : visibilityLevelOf(restriction, where)
}

// --- index remapping for SourceCodeInfo --------------------------------------
//
// SourceCodeInfo locations address elements by paths of (field number, index)
// pairs into the FileDescriptorProto. Removing array elements shifts the
// indices of their younger siblings, so every structural edit records an
// old-index -> new-index map here; remapSourceInfo() then drops the locations
// of removed elements and rewrites the indices of survivors.
function remapNode() {
  // field number -> { remap: Map<old,new>, keptOld: old indices in new order,
  //                   children: Map<old index, child node> }
  return { fields: new Map() }
}

// Filters `arr` in place per `keep(el, i)` and records the index remap on
// `node` under `fieldNo`. Returns the record so callers can attach child nodes
// (keyed by ORIGINAL index — `keptOld[newIdx]` recovers it).
function filterIndexed(node, fieldNo, arr, keep) {
  const remap = new Map()
  const keptOld = []
  const kept = []
  arr.forEach((el, i) => {
    if (keep(el, i)) {
      remap.set(i, kept.length)
      keptOld.push(i)
      kept.push(el)
    }
  })
  arr.length = 0
  arr.push(...kept)
  const entry = { remap, keptOld, children: new Map() }
  node.fields.set(fieldNo, entry)
  return entry
}

function remapSourceInfo(info, root) {
  if (!info) return
  info.location = (info.location ?? []).filter((loc) => {
    let node = root
    const path = loc.path ?? []
    for (let i = 0; i + 1 < path.length && node; i += 2) {
      const entry = node.fields.get(path[i])
      if (!entry) break // untouched subtree — keep the rest of the path as-is
      const oldIdx = path[i + 1]
      const newIdx = entry.remap.get(oldIdx)
      if (newIdx === undefined) return false // element was removed
      path[i + 1] = newIdx
      node = entry.children.get(oldIdx)
    }
    scrubLocation(loc)
    return true
  })
}

// --- internal comment scrubbing -----------------------------------------------
//
// grpc-gateway's remove_internal_comments convention: `(-- ... --)` spans are
// internal-only documentation. An unterminated `(--` swallows the rest of the
// comment (fail closed).
const INTERNAL_SPAN = /[ \t]*\(--[\s\S]*?--\)/g
const INTERNAL_OPEN = /[ \t]*\(--[\s\S]*$/

export function scrubComment(text) {
  return text.replace(INTERNAL_SPAN, '').replace(INTERNAL_OPEN, '')
}

function scrubLocation(loc) {
  if (loc.leadingComments !== undefined) {
    const t = scrubComment(loc.leadingComments)
    if (t.trim() === '') delete loc.leadingComments
    else loc.leadingComments = t
  }
  if (loc.trailingComments !== undefined) {
    const t = scrubComment(loc.trailingComments)
    if (t.trim() === '') delete loc.trailingComments
    else loc.trailingComments = t
  }
  if (loc.leadingDetachedComments?.length) {
    loc.leadingDetachedComments = loc.leadingDetachedComments
      .map(scrubComment)
      .filter((t) => t.trim() !== '')
  }
}

// --- custom option byte allowlist ----------------------------------------------

// Drops custom option bytes (descriptor unknown fields), keeping only the
// extension field numbers in `keepExts`.
function filterUnknownOptions(options, keepExts) {
  if (!options?.$unknown) return
  const kept = options.$unknown.filter((f) => keepExts.includes(f.no))
  if (kept.length > 0) options.$unknown = kept
  else delete options.$unknown
}

// --- the pass --------------------------------------------------------------------

export function applyVisibilitySurface(req, minLevel) {
  const genFiles = new Set(req.fileToGenerate ?? [])
  const files = req.protoFile ?? []

  // ---- index every type in the request (protoc includes all transitive deps).
  // fq name (no leading dot) -> { kind, desc, fileName, parentFq }
  const typeIndex = new Map()
  for (const fd of files) {
    const pkg = fd.package ? fd.package + '.' : ''
    const addEnum = (e, parentFq) => {
      typeIndex.set((parentFq ? parentFq + '.' : pkg) + e.name, {
        kind: 'enum',
        desc: e,
        fileName: fd.name,
        parentFq
      })
    }
    const addMessage = (m, parentFq) => {
      const fq = (parentFq ? parentFq + '.' : pkg) + m.name
      typeIndex.set(fq, {
        kind: 'message',
        desc: m,
        fileName: fd.name,
        parentFq
      })
      for (const nm of m.nestedType ?? []) addMessage(nm, fq)
      for (const ne of m.enumType ?? []) addEnum(ne, fq)
    }
    for (const m of fd.messageType ?? []) addMessage(m, undefined)
    for (const e of fd.enumType ?? []) addEnum(e, undefined)
  }

  // ---- keep decisions, computed once on the protoFile copies and applied to
  // every copy by name, so protoFile and sourceFileDescriptors stay identical.
  // Services survive only in generated files (filtered by level); a dependency
  // file's services are never emitted, so they are dropped outright instead of
  // anchoring types into the closure. Field/value filtering is uniform across
  // all files so traversal and pruning stay consistent.
  const svcKeep = new Map() // fileName -> Map(serviceName -> Set(methodName))
  const fieldDrop = new Set() // '<messageFq>#<fieldName>'
  const valueDrop = new Set() // '<enumFq>#<valueName>'
  const roots = [] // [typeName, via] from surviving methods

  for (const fd of files) {
    if (!genFiles.has(fd.name)) continue
    if (fd.publicDependency?.length || fd.weakDependency?.length) {
      throw new Error(
        `protoc-gen-es: visibility_level does not support 'import public'/'import weak' ` +
          `(found in ${fd.name}); use plain imports`
      )
    }
    const prefix = fd.package ? fd.package + '.' : ''
    const fileSvcs = new Map()
    svcKeep.set(fd.name, fileSvcs)
    for (const svc of fd.service ?? []) {
      const svcWhere = `${prefix}${svc.name}`
      if (levelOf(svc.options, `service ${svcWhere}`) < minLevel) continue
      const methods = new Set()
      for (const m of svc.method ?? []) {
        const where = `${svcWhere}.${m.name}`
        if (levelOf(m.options, where) < minLevel) continue
        methods.add(m.name)
        roots.push([m.inputType, where], [m.outputType, where])
      }
      // A service with no visible method disappears entirely — even its name
      // must not leak into the published surface.
      if (methods.size > 0) fileSvcs.set(svc.name, methods)
    }
  }
  for (const [fq, entry] of typeIndex) {
    if (entry.kind === 'message') {
      for (const f of entry.desc.field ?? []) {
        if (levelOf(f.options, `field ${fq}.${f.name}`) < minLevel)
          fieldDrop.add(`${fq}#${f.name}`)
      }
    } else {
      for (const v of entry.desc.value ?? []) {
        if (levelOf(v.options, `enum value ${fq}.${v.name}`) < minLevel)
          valueDrop.add(`${fq}#${v.name}`)
      }
    }
  }

  // ---- reachability from the surviving methods' request/response types.
  // Marking a nested type marks its containing types too (the descriptor
  // nesting must survive to host it); a marked message contributes all its
  // surviving fields' type references.
  const reachable = new Set()
  const queue = []
  const mark = (typeName, via) => {
    const fq = typeName.startsWith('.') ? typeName.slice(1) : typeName
    if (reachable.has(fq)) return
    const entry = typeIndex.get(fq)
    if (!entry) {
      throw new Error(
        `protoc-gen-es: type '${fq}' (referenced via ${via}) not found in the request`
      )
    }
    // A type explicitly restricted below the level but reachable from the
    // visible surface is a contradiction: generating it would leak it, dropping
    // it would break the surface. Fix the annotations (restrict the referencing
    // method/field too, or lift the type's restriction).
    if (
      genFiles.has(entry.fileName) &&
      levelOf(entry.desc.options, fq) < minLevel
    ) {
      throw new Error(
        `protoc-gen-es: ${entry.kind} '${fq}' is restricted below visibility level ` +
          `'${VISIBILITY_LEVELS[minLevel]}' but is reachable from the visible surface via ${via}`
      )
    }
    reachable.add(fq)
    if (entry.parentFq) mark(entry.parentFq, `${fq} (its containing type)`)
    if (entry.kind === 'message') queue.push(fq)
  }
  for (const [typeName, via] of roots) mark(typeName, via)
  while (queue.length > 0) {
    const fq = queue.shift()
    const { desc } = typeIndex.get(fq)
    for (const f of desc.field ?? []) {
      if (fieldDrop.has(`${fq}#${f.name}`)) continue
      if (TYPE_REF_KINDS.has(f.type) && f.typeName)
        mark(f.typeName, `field ${fq}.${f.name}`)
    }
  }

  const decisions = { typeIndex, svcKeep, fieldDrop, valueDrop, reachable }

  // Every file is rewritten — non-generated dependency files too (services
  // dropped via their absent svcKeep entry, types pruned to the same closure),
  // so the request protoc-gen-es sees never holds a dangling reference.
  for (const fd of files) {
    rewriteFile(fd, decisions)
  }
  for (const fd of req.sourceFileDescriptors ?? []) {
    if (genFiles.has(fd.name)) rewriteFile(fd, decisions)
  }

  // ---- fail-closed backstop: nothing below the level may survive in a file we
  // generate. The passes above make this structurally true; a bug here must
  // fail the build, never publish a leak.
  for (const fd of files) {
    if (genFiles.has(fd.name)) verifySurface(fd, minLevel)
  }
  verifyIntegrity(files)

  return req
}

// Post-rewrite referential-integrity walk over the WHOLE request: every kept
// field / method must resolve to a kept type. Structurally guaranteed by the
// pruning above; if a bug breaks that, fail with a descriptive error here
// rather than letting protoc-gen-es's registry die on a bare assertion.
function verifyIntegrity(files) {
  const kept = new Set()
  for (const fd of files) {
    const pkg = fd.package ? fd.package + '.' : ''
    const add = (m, fq) => {
      kept.add(fq)
      for (const nm of m.nestedType ?? []) add(nm, `${fq}.${nm.name}`)
      for (const e of m.enumType ?? []) kept.add(`${fq}.${e.name}`)
    }
    for (const m of fd.messageType ?? []) add(m, pkg + m.name)
    for (const e of fd.enumType ?? []) kept.add(pkg + e.name)
  }
  const check = (typeName, where, fileName) => {
    if (typeName && !kept.has(typeName.replace(/^\./, ''))) {
      throw new Error(
        `protoc-gen-es: internal error — ${where} (in ${fileName}) references ` +
          `'${typeName.replace(/^\./, '')}', which the visibility pass pruned; ` +
          `this is a bug in the pass`
      )
    }
  }
  for (const fd of files) {
    const pkg = fd.package ? fd.package + '.' : ''
    const walk = (m, fq) => {
      for (const f of m.field ?? []) {
        if (TYPE_REF_KINDS.has(f.type))
          check(f.typeName, `field ${fq}.${f.name}`, fd.name)
      }
      for (const nm of m.nestedType ?? []) walk(nm, `${fq}.${nm.name}`)
    }
    for (const m of fd.messageType ?? []) walk(m, pkg + m.name)
    for (const svc of fd.service ?? []) {
      for (const m of svc.method ?? []) {
        check(m.inputType, `method ${pkg}${svc.name}.${m.name} input`, fd.name)
        check(
          m.outputType,
          `method ${pkg}${svc.name}.${m.name} output`,
          fd.name
        )
      }
    }
  }
}

function rewriteFile(fd, d) {
  const pkg = fd.package ? fd.package + '.' : ''
  const root = remapNode()

  // message_type = 4
  const msgEntry = filterIndexed(root, 4, fd.messageType ?? [], (m) =>
    d.reachable.has(pkg + m.name)
  )
  ;(fd.messageType ?? []).forEach((m, i) => {
    msgEntry.children.set(
      msgEntry.keptOld[i],
      rewriteMessage(m, pkg + m.name, d)
    )
  })

  // enum_type = 5
  filterEnums(root, 5, fd.enumType ?? [], pkg, d)

  // service = 6
  const fileSvcs = d.svcKeep.get(fd.name) ?? new Map()
  const svcEntry = filterIndexed(root, 6, fd.service ?? [], (s) =>
    fileSvcs.has(s.name)
  )
  ;(fd.service ?? []).forEach((svc, i) => {
    const node = remapNode()
    svcEntry.children.set(svcEntry.keptOld[i], node)
    const methods = fileSvcs.get(svc.name)
    filterIndexed(node, 2, svc.method ?? [], (m) => methods.has(m.name))
    for (const m of svc.method ?? [])
      filterUnknownOptions(m.options, [HTTP_EXT_FIELD])
    filterUnknownOptions(svc.options, [])
  })

  // extension = 7: extension declarations never survive a published surface
  filterIndexed(root, 7, fd.extension ?? [], () => false)

  filterUnknownOptions(fd.options, [])

  // dependency = 3: recompute from the surviving type references
  const referenced = new Set()
  const collect = (typeName) => {
    const fq = typeName.startsWith('.') ? typeName.slice(1) : typeName
    const entry = d.typeIndex.get(fq)
    if (entry && entry.fileName !== fd.name) referenced.add(entry.fileName)
  }
  const collectMessage = (m) => {
    for (const f of m.field ?? []) {
      if (TYPE_REF_KINDS.has(f.type) && f.typeName) collect(f.typeName)
    }
    for (const nm of m.nestedType ?? []) collectMessage(nm)
  }
  ;(fd.messageType ?? []).forEach(collectMessage)
  for (const svc of fd.service ?? []) {
    for (const m of svc.method ?? []) {
      collect(m.inputType)
      collect(m.outputType)
    }
  }
  filterIndexed(root, 3, fd.dependency ?? [], (dep) => referenced.has(dep))

  remapSourceInfo(fd.sourceCodeInfo, root)
}

function rewriteMessage(m, fq, d) {
  const node = remapNode()

  // field = 2
  filterIndexed(
    node,
    2,
    m.field ?? [],
    (f) => !d.fieldDrop.has(`${fq}#${f.name}`)
  )

  // oneof_decl = 8: drop oneofs emptied by field filtering (incl. the synthetic
  // oneof of a removed proto3 `optional` field) and reindex the survivors.
  // NB: protobuf-es exposes unset fields as their zero value via the prototype,
  // so presence of oneof_index must be tested with Object.hasOwn, not undefined.
  const usedOneofs = new Set()
  for (const f of m.field ?? []) {
    if (Object.hasOwn(f, 'oneofIndex')) usedOneofs.add(f.oneofIndex)
  }
  const oneofEntry = filterIndexed(node, 8, m.oneofDecl ?? [], (_, i) =>
    usedOneofs.has(i)
  )
  for (const f of m.field ?? []) {
    if (Object.hasOwn(f, 'oneofIndex')) {
      const remapped = oneofEntry.remap.get(f.oneofIndex)
      if (remapped === undefined) {
        throw new Error(
          `protoc-gen-es: internal error — field ${fq}.${f.name} lost its oneof`
        )
      }
      f.oneofIndex = remapped
    }
    filterUnknownOptions(f.options, [])
  }
  for (const o of m.oneofDecl ?? []) filterUnknownOptions(o.options, [])

  // nested_type = 3
  const nestedEntry = filterIndexed(node, 3, m.nestedType ?? [], (nm) =>
    d.reachable.has(`${fq}.${nm.name}`)
  )
  ;(m.nestedType ?? []).forEach((nm, i) => {
    nestedEntry.children.set(
      nestedEntry.keptOld[i],
      rewriteMessage(nm, `${fq}.${nm.name}`, d)
    )
  })

  // enum_type = 4
  filterEnums(node, 4, m.enumType ?? [], `${fq}.`, d)

  // extension = 6
  filterIndexed(node, 6, m.extension ?? [], () => false)

  for (const r of m.extensionRange ?? []) filterUnknownOptions(r.options, [])
  filterUnknownOptions(m.options, [])
  return node
}

function filterEnums(node, fieldNo, enums, prefix, d) {
  const entry = filterIndexed(node, fieldNo, enums, (e) =>
    d.reachable.has(prefix + e.name)
  )
  enums.forEach((e, i) => {
    const fq = prefix + e.name
    const child = remapNode()
    entry.children.set(entry.keptOld[i], child)
    filterIndexed(
      child,
      2,
      e.value ?? [],
      (v) => !d.valueDrop.has(`${fq}#${v.name}`)
    )
    if ((e.value ?? []).length === 0) {
      throw new Error(
        `protoc-gen-es: every value of enum '${fq}' is restricted below the visibility ` +
          `level; restrict the enum itself (or every field using it) instead`
      )
    }
    for (const v of e.value ?? []) filterUnknownOptions(v.options, [])
    filterUnknownOptions(e.options, [])
  })
}

// Post-rewrite assertion over a file we generate. Throws on the first leak.
function verifySurface(fd, minLevel) {
  const fail = (what) => {
    throw new Error(
      `protoc-gen-es: internal error — ${what} survived a ` +
        `${VISIBILITY_LEVELS[minLevel]} visibility surface; this is a bug in the ` +
        `visibility pass, do not publish this output`
    )
  }
  const check = (kind, options, where) => {
    if (levelOf(options, where) < minLevel)
      fail(`${kind} '${where}' restricted below the level`)
  }
  const walkEnum = (e, fq) => {
    check('enum', e.options, fq)
    if ((e.value ?? []).length === 0) fail(`empty enum '${fq}'`)
    for (const v of e.value ?? [])
      check('enum value', v.options, `${fq}.${v.name}`)
  }
  const walkMessage = (m, fq) => {
    check('message', m.options, fq)
    for (const f of m.field ?? []) check('field', f.options, `${fq}.${f.name}`)
    for (const nm of m.nestedType ?? []) walkMessage(nm, `${fq}.${nm.name}`)
    for (const e of m.enumType ?? []) walkEnum(e, `${fq}.${e.name}`)
    if ((m.extension ?? []).length > 0) fail(`extension declaration in '${fq}'`)
  }
  const pkg = fd.package ? fd.package + '.' : ''
  for (const m of fd.messageType ?? []) walkMessage(m, pkg + m.name)
  for (const e of fd.enumType ?? []) walkEnum(e, pkg + e.name)
  if ((fd.extension ?? []).length > 0)
    fail(`extension declaration in '${fd.name}'`)
  for (const svc of fd.service ?? []) {
    check('service', svc.options, pkg + svc.name)
    if ((svc.method ?? []).length === 0)
      fail(`empty service '${pkg}${svc.name}'`)
    for (const m of svc.method ?? [])
      check('method', m.options, `${pkg}${svc.name}.${m.name}`)
  }
}
