name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted]
    timeout-minutes: 90
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      release_version: ${{ steps.vars.outputs.tag }}
      env: ${{ steps.vars.outputs.env }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v5
      - name: 'Set up Python'
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Set output
        id: vars
        run: |
          if [[ "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
            echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
            echo "env=staging" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
            echo "env=test" >> $GITHUB_OUTPUT
          fi
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Clean app source cache
        run:  ./scripts/clean-bazel-bin-stale-files.sh
      - name: Build & Test All
        run: bazel test --config=ci //...
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      - name: Wait bazel cache clean
        run: |
          for i in $(seq 1 10); do
            bazel info | grep gc
            sleep 1
          done
