// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: processor/protos/processor.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Processor_Start_FullMethodName                    = "/processor.Processor/Start"
	Processor_Stop_FullMethodName                     = "/processor.Processor/Stop"
	Processor_GetConfig_FullMethodName                = "/processor.Processor/GetConfig"
	Processor_ProcessBindings_FullMethodName          = "/processor.Processor/ProcessBindings"
	Processor_ProcessBindingsStream_FullMethodName    = "/processor.Processor/ProcessBindingsStream"
	Processor_PreprocessBindingsStream_FullMethodName = "/processor.Processor/PreprocessBindingsStream"
)

// ProcessorClient is the client API for Processor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessorClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetConfig(ctx context.Context, in *ProcessConfigRequest, opts ...grpc.CallOption) (*ProcessConfigResponse, error)
	ProcessBindings(ctx context.Context, in *ProcessBindingsRequest, opts ...grpc.CallOption) (*ProcessBindingResponse, error)
	ProcessBindingsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessStreamRequest, ProcessStreamResponse], error)
	PreprocessBindingsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PreprocessStreamRequest, PreprocessStreamResponse], error)
}

type processorClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessorClient(cc grpc.ClientConnInterface) ProcessorClient {
	return &processorClient{cc}
}

func (c *processorClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Processor_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Processor_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) GetConfig(ctx context.Context, in *ProcessConfigRequest, opts ...grpc.CallOption) (*ProcessConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessConfigResponse)
	err := c.cc.Invoke(ctx, Processor_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) ProcessBindings(ctx context.Context, in *ProcessBindingsRequest, opts ...grpc.CallOption) (*ProcessBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessBindingResponse)
	err := c.cc.Invoke(ctx, Processor_ProcessBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorClient) ProcessBindingsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessStreamRequest, ProcessStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Processor_ServiceDesc.Streams[0], Processor_ProcessBindingsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessStreamRequest, ProcessStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Processor_ProcessBindingsStreamClient = grpc.BidiStreamingClient[ProcessStreamRequest, ProcessStreamResponse]

func (c *processorClient) PreprocessBindingsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PreprocessStreamRequest, PreprocessStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Processor_ServiceDesc.Streams[1], Processor_PreprocessBindingsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PreprocessStreamRequest, PreprocessStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Processor_PreprocessBindingsStreamClient = grpc.BidiStreamingClient[PreprocessStreamRequest, PreprocessStreamResponse]

// ProcessorServer is the server API for Processor service.
// All implementations must embed UnimplementedProcessorServer
// for forward compatibility.
type ProcessorServer interface {
	Start(context.Context, *StartRequest) (*emptypb.Empty, error)
	Stop(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetConfig(context.Context, *ProcessConfigRequest) (*ProcessConfigResponse, error)
	ProcessBindings(context.Context, *ProcessBindingsRequest) (*ProcessBindingResponse, error)
	ProcessBindingsStream(grpc.BidiStreamingServer[ProcessStreamRequest, ProcessStreamResponse]) error
	PreprocessBindingsStream(grpc.BidiStreamingServer[PreprocessStreamRequest, PreprocessStreamResponse]) error
	mustEmbedUnimplementedProcessorServer()
}

// UnimplementedProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessorServer struct{}

func (UnimplementedProcessorServer) Start(context.Context, *StartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedProcessorServer) Stop(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedProcessorServer) GetConfig(context.Context, *ProcessConfigRequest) (*ProcessConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedProcessorServer) ProcessBindings(context.Context, *ProcessBindingsRequest) (*ProcessBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBindings not implemented")
}
func (UnimplementedProcessorServer) ProcessBindingsStream(grpc.BidiStreamingServer[ProcessStreamRequest, ProcessStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessBindingsStream not implemented")
}
func (UnimplementedProcessorServer) PreprocessBindingsStream(grpc.BidiStreamingServer[PreprocessStreamRequest, PreprocessStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PreprocessBindingsStream not implemented")
}
func (UnimplementedProcessorServer) mustEmbedUnimplementedProcessorServer() {}
func (UnimplementedProcessorServer) testEmbeddedByValue()                   {}

// UnsafeProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessorServer will
// result in compilation errors.
type UnsafeProcessorServer interface {
	mustEmbedUnimplementedProcessorServer()
}

func RegisterProcessorServer(s grpc.ServiceRegistrar, srv ProcessorServer) {
	// If the following call pancis, it indicates UnimplementedProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Processor_ServiceDesc, srv)
}

func _Processor_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Processor_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Processor_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).Stop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Processor_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).GetConfig(ctx, req.(*ProcessConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_ProcessBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorServer).ProcessBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Processor_ProcessBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorServer).ProcessBindings(ctx, req.(*ProcessBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processor_ProcessBindingsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessorServer).ProcessBindingsStream(&grpc.GenericServerStream[ProcessStreamRequest, ProcessStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Processor_ProcessBindingsStreamServer = grpc.BidiStreamingServer[ProcessStreamRequest, ProcessStreamResponse]

func _Processor_PreprocessBindingsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessorServer).PreprocessBindingsStream(&grpc.GenericServerStream[PreprocessStreamRequest, PreprocessStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Processor_PreprocessBindingsStreamServer = grpc.BidiStreamingServer[PreprocessStreamRequest, PreprocessStreamResponse]

// Processor_ServiceDesc is the grpc.ServiceDesc for Processor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Processor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processor.Processor",
	HandlerType: (*ProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Processor_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Processor_Stop_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Processor_GetConfig_Handler,
		},
		{
			MethodName: "ProcessBindings",
			Handler:    _Processor_ProcessBindings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessBindingsStream",
			Handler:       _Processor_ProcessBindingsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PreprocessBindingsStream",
			Handler:       _Processor_PreprocessBindingsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "processor/protos/processor.proto",
}

const (
	ProcessorV3_Start_FullMethodName                 = "/processor.ProcessorV3/Start"
	ProcessorV3_GetConfig_FullMethodName             = "/processor.ProcessorV3/GetConfig"
	ProcessorV3_UpdateTemplates_FullMethodName       = "/processor.ProcessorV3/UpdateTemplates"
	ProcessorV3_ProcessBindingsStream_FullMethodName = "/processor.ProcessorV3/ProcessBindingsStream"
)

// ProcessorV3Client is the client API for ProcessorV3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessorV3Client interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetConfig(ctx context.Context, in *ProcessConfigRequest, opts ...grpc.CallOption) (*ProcessConfigResponse, error)
	UpdateTemplates(ctx context.Context, in *UpdateTemplatesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ProcessBindingsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessStreamRequest, ProcessStreamResponseV3], error)
}

type processorV3Client struct {
	cc grpc.ClientConnInterface
}

func NewProcessorV3Client(cc grpc.ClientConnInterface) ProcessorV3Client {
	return &processorV3Client{cc}
}

func (c *processorV3Client) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProcessorV3_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorV3Client) GetConfig(ctx context.Context, in *ProcessConfigRequest, opts ...grpc.CallOption) (*ProcessConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessConfigResponse)
	err := c.cc.Invoke(ctx, ProcessorV3_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorV3Client) UpdateTemplates(ctx context.Context, in *UpdateTemplatesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProcessorV3_UpdateTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processorV3Client) ProcessBindingsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessStreamRequest, ProcessStreamResponseV3], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessorV3_ServiceDesc.Streams[0], ProcessorV3_ProcessBindingsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessStreamRequest, ProcessStreamResponseV3]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessorV3_ProcessBindingsStreamClient = grpc.BidiStreamingClient[ProcessStreamRequest, ProcessStreamResponseV3]

// ProcessorV3Server is the server API for ProcessorV3 service.
// All implementations must embed UnimplementedProcessorV3Server
// for forward compatibility.
type ProcessorV3Server interface {
	Start(context.Context, *StartRequest) (*emptypb.Empty, error)
	GetConfig(context.Context, *ProcessConfigRequest) (*ProcessConfigResponse, error)
	UpdateTemplates(context.Context, *UpdateTemplatesRequest) (*emptypb.Empty, error)
	ProcessBindingsStream(grpc.BidiStreamingServer[ProcessStreamRequest, ProcessStreamResponseV3]) error
	mustEmbedUnimplementedProcessorV3Server()
}

// UnimplementedProcessorV3Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessorV3Server struct{}

func (UnimplementedProcessorV3Server) Start(context.Context, *StartRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedProcessorV3Server) GetConfig(context.Context, *ProcessConfigRequest) (*ProcessConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedProcessorV3Server) UpdateTemplates(context.Context, *UpdateTemplatesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplates not implemented")
}
func (UnimplementedProcessorV3Server) ProcessBindingsStream(grpc.BidiStreamingServer[ProcessStreamRequest, ProcessStreamResponseV3]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessBindingsStream not implemented")
}
func (UnimplementedProcessorV3Server) mustEmbedUnimplementedProcessorV3Server() {}
func (UnimplementedProcessorV3Server) testEmbeddedByValue()                     {}

// UnsafeProcessorV3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessorV3Server will
// result in compilation errors.
type UnsafeProcessorV3Server interface {
	mustEmbedUnimplementedProcessorV3Server()
}

func RegisterProcessorV3Server(s grpc.ServiceRegistrar, srv ProcessorV3Server) {
	// If the following call pancis, it indicates UnimplementedProcessorV3Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessorV3_ServiceDesc, srv)
}

func _ProcessorV3_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorV3Server).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessorV3_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorV3Server).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessorV3_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorV3Server).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessorV3_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorV3Server).GetConfig(ctx, req.(*ProcessConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessorV3_UpdateTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessorV3Server).UpdateTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessorV3_UpdateTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessorV3Server).UpdateTemplates(ctx, req.(*UpdateTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessorV3_ProcessBindingsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessorV3Server).ProcessBindingsStream(&grpc.GenericServerStream[ProcessStreamRequest, ProcessStreamResponseV3]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessorV3_ProcessBindingsStreamServer = grpc.BidiStreamingServer[ProcessStreamRequest, ProcessStreamResponseV3]

// ProcessorV3_ServiceDesc is the grpc.ServiceDesc for ProcessorV3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessorV3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processor.ProcessorV3",
	HandlerType: (*ProcessorV3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _ProcessorV3_Start_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ProcessorV3_GetConfig_Handler,
		},
		{
			MethodName: "UpdateTemplates",
			Handler:    _ProcessorV3_UpdateTemplates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessBindingsStream",
			Handler:       _ProcessorV3_ProcessBindingsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "processor/protos/processor.proto",
}
